### ISSUE TITLE
Failed to parse archive, error: profile not exists

### ISSUE THREAD

**Issue by soshman** [bitrise-steplib/steps-xcode-archive#130]
I'm trying to build workflow for our app.
We have same code to support many clients, so we generate our cordova projects during build time.

Everything seem to be set correctly, but during iOS archive I get Error Code: 1
And code message: Failed to parse archive, error: profile not exists at ...

Build link: https://app.bitrise.io/build/6cec9699b64db1a3
Xcode Archive & Export for iOS: latest version (2.4.15)

**Comment by bitce** [comment]
Hi @soshman sorry to hear about the issue, and thanks for contacting us!

We are looking into it and will reply here as soon as we have something!

**Comment by soshman** [comment]
This error seems to be connected to the new release of XCode. I encountered this problem with my local environment after update. Cordova projects are not compatible with XCode 10.

Statement:
https://github.com/apache/cordova-ios/issues/407

In short, it is caused by new build system, which became default after update. Workaround for this is adding new flag to xcodebuild: -UseModernBuildSystem=0.

**Comment by bitce** [comment]
Hi there!

Glad to hear you've found this, we've been experimenting with this (UseModernBuildSystem=0) option for the last few days but it's hard to say what portion of actual issues did this solve, in case it was a compatibility issue alone, I'd say this is a solution as opposed to a workaround.

Anyhow, I hope things will be running smoothly from now! 🤞

**Comment by bitce** [comment]
Hey @pjwelcome! Please insert a " -UseModernBuildSystem=NO "  flag to the “Additional options for xcodebuild to call” input in the “Debug” section of the related Xcode step and run the build that way

**Comment by pjwelcome** [comment]
Thanks so much @bitce . This was helpful.

**Comment by gabeosx** [comment]
I am getting this error when running codesigndoc - is there a way to force codesigndoc to use -UseModernBuildSystem=NO

**Comment by fehersanyi-bitrise** [comment]
Hy @gabeosx codesigndoc should be used locally after you export an appropriate ipa, not in the build 🤔
