### ISSUE TITLE
Strange Default Value in UI for artifact_name

### ISSUE THREAD

**Issue by joh-klein** [bitrise-steplib/steps-xcode-archive#138]
The default value in the field for "Generated Artifact Name" is `${scheme}` – shouldn't it be `$BITRISE_SCHEME`?

**Comment by bitce** [comment]
Hi @joh-klein! Could you send us a build URL so we're definitely seeing the same thing as you? :)

**Comment by joh-klein** [comment]
I think this is the culprit:
https://github.com/bitrise-io/steps-xcode-archive/blob/master/step.yml#L198

**Comment by lszucs** [comment]
Hello @joh-klein,

You are right, nice catch! Thanks for pointing this out! :) I shall open a bug report.

Also, for your information: we are moving our issue management from GitHub to Discourse (https://discuss.bitrise.io). GitHub issues are left enabled for technical reasons, but it is recommended that you open bug reports/feature requests there in the future.
