### ISSUE TITLE
Unable to sign tvOS project

### ISSUE THREAD

**Issue by wqz-leo** [bitrise-steplib/steps-xcode-archive#142]
Hi,

I have 2 individual projects for iOS and tvOS. Both have the same bundle ID.

Recently `iOS auto provision` step had some issue with `adhoc` and been fixed in v1.2.3 and my iOS project works fine after updates.
However, after updating the step in tvOS project, it's no longer build anymore.

I have tried several things:
1. Set `generate_profiles: yes` in auto provision step
2. Do not generate profile in auto provision step and upload profiles manually
3. Same as step 2 but set `-allowProvisioningUpdates` in archive step

Actual results are:
1. Generated 4 profiles in apple developer portal, but archive step failed with error `error: exportArchive: "xxxx.appex" requires a provisioning profile with the App Groups feature.`. 
Please find the log for [auto generate profile.log](https://github.com/bitrise-io/steps-xcode-archive/files/2735183/auto.generate.profile.log)

2. Uploaded 4 profiles manually (Development, Development Topshelf, Adhoc, Adhoc Topshelf) but build failed with `error: No profiles for 'co.massive.axis.qa2' were found: Xcode couldn't find any tvOS App Development provisioning profiles matching 'co.massive.axis.qa2'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Axis_tvOS')`
Please find the log for [manually upload profiles.log](https://github.com/bitrise-io/steps-xcode-archive/files/2735189/manually.upload.profiles.log)

3. Failed with `error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'TARGET_topshelf')` (2 errors in total, the second one is in target itself). However, account is connected via `project -> Team -> Connected Apple Developer Portal Account`
Please find log for [allowProvisioningUpdates.log](https://github.com/bitrise-io/steps-xcode-archive/files/2735193/allowProvisioningUpdates.log)

Any suggestions how should I fix this issue?

Many thanks!

**Comment by lpusok** [comment]
Hi @wangqingzhouleo,
In the result 1, the profiles are filtered out in the xcode-archive step, but would need to see the debug log to know why.
In result 2, xcodebuild fails due not finding tvOS profiles, are you sure that those were not iOS profiles with the same bundle ID by mistake? Not sure why it happens.
For result 3, the `-allowProvisioningUpdates` flag does not work in a CI environment, as it requires a signed in developer account in Xcode, and that is not supported.
For manual provisioning  using the codesigndoc tool is recomended(https://devcenter.bitrise.io/code-signing/ios-code-signing/collecting-files-with-codesigndoc/).
For the automatic provisioning, archiving and exporting locally, than using the Exportoptions.plist contents as a parameter for the xcode-archive to replicate the build usually solves the issues. (with the `generate_profiles: no` option)
i realise that the tvOS seems to complicate things in this case, more investigation is needed to identify the issue.

**Comment by godrei** [comment]
Hi @wqz-leo ,
sorry for the inconvenience.

It seems iOS Auto Provision step sees 2 targets to sign:
- Axis_tvOS (co.massive.axis.qa2)
- Axis_tvOS_topshelf (co.massive.axis.qa2.topshelf)

But Xcode Archives finds 3 more (co.massive.axis.Axis-SDK-tvOS, co.massive.axis.Axis-API-tvOS, co.massive.axis.Axis-Analytics-tvOS). Most likly these extra 3 targets are not executable targets, which needs codesigning and that is the source of one issue.

Xcode Archives tries to set up the export option for 5 targets, but iOS Auto Provision step prepared profiles for 2 targets, so the archives step fails at that stage:

```
Failed to find Codesign Groups
```

I will create a task to fix this. Till the fix arrives, you can work around this by manually putting together the exportOptions and passing to the Xcode Archive step as step input: `Custom export options plist content` .

Based on your build log it should look like:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>compileBitcode</key>
        <false/>
        <key>method</key>
        <string>ad-hoc</string>
        <key>provisioningProfiles</key>
        <dict>
            <key>co.massive.axis.qa2</key>
            <string>Bitrise ad-hoc - (co.massive.axis.qa2)</string>
            <key>co.massive.axis.qa2.topshelf</key>
            <string>Bitrise ad-hoc - (co.massive.axis.qa2.topshelf)</string>
        </dict>
    </dict>
</plist>
```

So i hope using the generate_profiles: yes in auto provision step + xcode archive with custom export options will work.

**Comment by godrei** [comment]
@wqz-leo you use a quite old Xcode Archive step version, for first could you please try to use: enerate_profiles: yes in auto provision step + latest xcode archive version without custom export options?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @wqz-leo please let us know if we can help with anything by opening a new issue!
