### ISSUE TITLE
Archive failed, error: exit status 65

### ISSUE THREAD

**Issue by mjurfest** [bitrise-steplib/steps-xcode-archive#144]
Hi, i am getting this error when trying to run bitrise.

```
The following build commands failed:
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Archive failed, error: exit status 65
xcode-archive@2.4.19 (exit code: 1)  
``` 

Can you please help me?

**Comment by fehersanyi-bitrise** [comment]
Hy @mjurfest 
Could you please send us the url of this build, so we can check the full logs for some more details?

**Comment by mjurfest** [comment]
@fehersanyi-bitrise I have already fixed it. Thank you.

**Comment by simformsolutions** [comment]
@mjurfest 
Can you please tell me how did you fix it?

**Comment by mjurfest** [comment]
@simformsolutions it wasn't a bitrise issue. The issue was in my code. It worked fine locally but it didn't on bitrise. I don't remember exactly the reason but I guess that was because of duplicated files. Try to check the logs to see if you dont have any duplicated files. In case you have: Go to Project --> Build Phases --> Search that file --> Delete duplicate

**Comment by dyegos** [comment]
I'm also having this issue, @fehersanyi-bitrise is this URL enough https://app.bitrise.io/build/8f0309baa25c1993?
