### ISSUE TITLE
Failed to parse archive, error: failed to find main app

### ISSUE THREAD

**Issue by tomesm** [bitrise-steplib/steps-xcode-archive#145]
Hi,
Im experiencing this problem when building my app. The same problem occurs when using codesigndoc tool on the same app locally on my mac. 

I've just google similar problem [here](https://discuss.bitrise.io/t/building-ios-frameworks-using-bitrise/3987), but it does not seem to related to my problem as I am not building a framework.

I have also tried to use "-UseModernBuildSystem=NO " flag as Debug additional option without any success.

[See](https://app.bitrise.io/build/5c2b782c57c8aa91) the build URL.

Also attaching the log. [5c2b782c57c8aa91.log](https://github.com/bitrise-io/steps-xcode-archive/files/2799045/5c2b782c57c8aa91.log)

I will appretiate any help here.

**Comment by fehersanyi-bitrise** [comment]
Hello @tomesm ! Could you please enable support user to the app, I would like to check some setups, maybe I can find the issue there.

**Comment by tomesm** [comment]
Hi @fehersanyi-bitrise , its enabled.

**Comment by fehersanyi-bitrise** [comment]
Hy there!

I have a suspicion that the .app file is actually a folder lower then what we would expect, it could be checked with a tree command in a script after the archive step like `tree /var/folders/90/`
if it is in the wrong folder then we will need to rework the step, for this might be a bug on our side.

**Comment by fehersanyi-bitrise** [comment]
Hy @tomesm then could you look for the file with `mdfind -name NameOfTheApp.xcodeproj` ?

**Comment by tomesm** [comment]
@fehersanyi-bitrise You mean put it to the YAML config file?

**Comment by bitce** [comment]
Hi! @tomesm! I think he meant to simply run this as a script step on the VM, it shouldn't make a difference whether to use the Workflow Editor UI or the .yml editor

**Comment by tomesm** [comment]
@bitce @fehersanyi-bitrise I tried to use `mdfind` before build and after archive phase (together with `tree`) command (script step 5, see the log).

It seems to me quite clearly that the .app file is in the expected location (under NameOfApp.xcarchive/Products/Applications/

Perhaps there is something wrong with the mattern matching? Please, look into the log. I really do not know what else I should do from my side to solve this issue.

**Comment by fehersanyi-bitrise** [comment]
Hy @tomesm 
I checked the logs and the step looks for the .xcarchive not the .xcodeproj file 🤔

**Comment by tomesm** [comment]
@fehersanyi-bitrise so, it's a bug then?

**Comment by tomesm** [comment]
@fehersanyi-bitrise @bitce I tried to deploy another our app with the same error:

https://app.bitrise.io/build/2100b022d668aef6

**Comment by fehersanyi-bitrise** [comment]
I'm afraid yes, I will get the the tooling team involved in the issue.

**Comment by trapacska** [comment]
Hey @tomesm !

I think that you might have your *.app generated on a different location in the xcarchive than the step searches for. The only way to check is if you are creating an archive locally, and you try to find the app manually, after that please get back to us with the path where you found the .app so we can see if the step want to find the app correctly or not.

Thanks in advance!

**Comment by tomesm** [comment]
Hi @trapacska @fehersanyi-bitrise I have used bitrise-cli localy on my mac. 

We do use several schemas [Alpha], [Beta] etc, and do not use automatic signing. 

This is the output

`Failed to parse archive, error: failed to find main app, using pattern: /var/folders/cr/hxzp0ksx6slbyjlgm3ttwkk00000gn/T/__archive__053541915/[Alpha] Vocabulary Miner.xcarchive/Products/Applications/*.app`

I have checked manually the folder and the .app file is there:

![screenshot 2019-02-18 at 14 40 44](https://user-images.githubusercontent.com/6170316/52954953-bca65980-338b-11e9-8c25-4cf048167e10.png)

**Comment by fehersanyi-bitrise** [comment]
Hy @tomesm 
the tooling team created a card to fix this bug, they will get back to you when it is done! 🙃

**Comment by tomesm** [comment]
@fehersanyi-bitrise ok, thanks :)

**Comment by lpusok** [comment]
Hello @tomesm !
There is new version of xcode-archive currently rolling out (version 2.4.21, https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.4.21) that includes a fix for the issue.

**Comment by tomesm** [comment]
Hi @lpusok Thanks, it's working now :)
