### ISSUE TITLE
Add The ability to Export the AppStoreInfo.plist

### ISSUE THREAD

**Issue by ccarranzaD3** [bitrise-steplib/steps-xcode-archive#150]
Would it be possible to add an option for the generateAppStoreInformation value in the ExportOptions.plist file? The options makes  Xcode output the AppStoreInfo.plist file along with the build. 

My use case would be to upload my app on a different linux machine. In order to upload a binary through anything but a Mac you need to supply the AppStoreInfo.plist file. This can be generated at build time by supplying this key in the ExportOptions.plist.

Unfortunately as it stands there isn't a way to just tack on that extra key to the options that your current script generates.

I'm not well versed in go, but would be happy to submit a PR if this is acceptable.

**Comment by fehersanyi-bitrise** [comment]
Hello there, could you please create this feature request here? https://discuss.bitrise.io/c/feature-request

also, PR-s are always welcome so if you think you would like to do it then go ahead! 🙃

**Comment by zombieleet** [comment]
what is the current status of this please?

**Comment by non-binary** [comment]
From what I can see internally, no progress has been made on this. We welcome PRs however if this is something you would like sooner

**Comment by zombieleet** [comment]
I would have loved to, but I am not familiar with Go :disappointed: . But Thanks for the update :smiley:
