### ISSUE TITLE
Archive an SDK without exporting?

### ISSUE THREAD

**Issue by enoelboostmi** [bitrise-steplib/steps-xcode-archive#153]
I have an SDK that I've put under CI on bitrise. when I run the Archive and export step, the archive works but it fails when trying to export because it can't find the IPA. Is there a way to simply archive and not look for an .ipa?

Is there something else I'm not understanding?

**Comment by bitce** [comment]
HI @enoelboostmi!

In case you don't want to export, maybe you could simply remove the Deploy to Bitrise.io step? Or do you need it for some othe reason?

**Comment by matuslittva** [comment]
@bitce Hello, I think I ran into same case as @enoelboostmi, I need just to export unsigned xcarchive without .ipa, is this possible?

**Comment by bitce** [comment]
Hi @matuslittva!

It should be entirely possible. The following commands should produce that exactly:

`xcodebuild -workspace <projectName>.xcworkspace -scheme <projectName> -configuration Release clean archive -archivePath buildArchive/<projectName>.xcarchive CODE_SIGN_IDENTITY=”” CODE_SIGNING_REQUIRED=NO`

Make sure the archive gets located in the deploy directory / or modify the directory of the Bitrise Deploy step, for the file to be available online.
