### ISSUE TITLE
Current working directory is incorrectly copied into dSYM zip file

### ISSUE THREAD

**Issue by connor-alphero** [bitrise-steplib/steps-xcode-archive#155]
## Description
I have a project (running Xcode 10.2.x, macOS 10.14 (Mojave) stack) that uses the xcode-archive and deploy to bitrise steps to export the app's desymbolication files as a zip file. The zip file ends up being ~300MB and contains a collection of dSYMs + a copy of the project source code. I would expect the dsym zip to contain just the dsym files.

## Fault
I have identified the problematic code that spans two files

https://github.com/bitrise-io/go-xcode/blob/51984334e0fb83bf66588acf87f09c5ac624874b/xcarchive/ios.go#L329-L350

`FindDSYMs()` defaults to an empty string if it cannot find a file ending with `.app.dsym`
The fact it returns an empty string if it cannot location a `.app.dsym` causes an issue in the xcode archive step.

https://github.com/bitrise-steplib/steps-xcode-archive/blob/95e00f357cea01ff520b5103bc9a5a3da2055e32/main.go#L903-L940

On line 903, `FindDSYMs()` is called to locate the dsym files for the app and frameworks. The app's dsym path is held in `appDSYM`.
On line 917, the `appDSYM` is copied into dsymDir. If `appDSYM` is an empty string, like it can be if there isn't a `.app.dsym` file, it copies the entire current working directory.

Ideally, there would be a check on the `appDSYM` before it performs the copy to make sure it does not copy the current working directory.

**Comment by connor-alphero** [comment]
I have discovered why my project is not generating a `.app.dsym`. The Debug Information Format was set to just 'DWARF' rather than 'DWARF with dSYM File'. After changing this setting the an `.app.dsym` file was detected and to dsym zip contained just dsyms.

It feels as though a warning or fail should occur in the event an `.app.dsym` file was not located before it copies the whole project.

**Comment by fehersanyi-bitrise** [comment]
Hy @connor-alphero 
I'm glad to hear you found the solution!🎉
also thanks for the heads up, we will check out the possibilities of emitting a warning in this case. 🙃

**Comment by lszucs** [comment]
Hi @connor-alphero,

Thanks for the report! Can you please tell me which version of the step you use and whether the issue persist with the latest version?
