### ISSUE TITLE
Failed to analyze archive, error: profile not exists

### ISSUE THREAD

**Issue by srashish** [bitrise-steplib/steps-xcode-archive#159]
I'm facing trouble while setting up codesign for my Meteor generated project while using curl for Xcode:

Command I'm using:-
`bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-io/codesigndoc/master/_scripts/install_wrap-xcode.sh)"
 => Creating a temporary directory for codesigndoc ...`

But it fails at finding some mobileprovisioning profile at a specific location.

Complete Stack Trace :-
`Xcode (xcodebuild) version: Xcode 10.1 (Build version 10B61)

🔦  Running an Xcode Archive, to get all the required code signing settings...
$ xcodebuild "-workspace" "/Users/ashishsr/wayforward/therapy-app-builds/wayforward-dev-ios-build-2019-05-20-2323/ios/project/DEV-wayForward.xcworkspace" "-scheme" "DEV-wayForward" "clean" "archive" "-archivePath" "/var/folders/r6/5b2x55f15w192pz1tzrhl6mc0000gp/T/__codesigndoc__034325115/DEV-wayForward.xcarchive"
.........................................................

💡  Saving xcodebuild output into file: /Users/ashishsr/wayforward/therapy-app-builds/wayforward-dev-ios-build-2019-05-20-2323/ios/project/codesigndoc_exports/xcodebuild-output.log

🔦  Analyzing the archive, to get export code signing settings...
failed to analyze archive, error: profile not exists at: /var/folders/r6/5b2x55f15w192pz1tzrhl6mc0000gp/T/__codesigndoc__034325115/DEV-wayForward.xcarchive/Products/Applications/DEV-wayForward.app/embedded.mobileprovision`

**Comment by bitce** [comment]
Hi @srashish! In this case this thread would be probably better suited here: https://github.com/bitrise-io/codesigndoc/issues 

But in any event, are you able to otherwise archive from Xcode? I'm not entirely sure if a Meteor project can work with this tool, but I'm looking into it

**Comment by srashish** [comment]
> Hi @srashish! In this case this thread would be probably better suited here: https://github.com/bitrise-io/codesigndoc/issues
> 
> But in any event, are you able to otherwise archive from Xcode? I'm not entirely sure if a Meteor project can work with this tool, but I'm looking into it

Hi bitce, yes I'm able to archive using Xcode and was also able to upload it to testflight using fastlane, but it had some issues on CircleCI so I switched to bitrise.

**Comment by bitce** [comment]
I see! I'll try to see if we can recreate this problem, in the while can you export these manually without the tool so you can start building?
