### ISSUE TITLE
dSYM zip file include more files than it should

### ISSUE THREAD

**Issue by odemolliens** [bitrise-steplib/steps-xcode-archive#160]
This issue is related to this part of the code:
https://github.com/bitrise-steplib/steps-xcode-archive/blob/54295929c7fe6f0beb231ef19c680389839cd1f2/main.go#L932

In case of a react-native project,

I have discover that the dSYM zip folder generate by this steps include other files than dSYM only and that's explain why my zip is so big (screenshot from a remote bitrise machine):
<img width="656" alt="Screenshot 2019-07-26 at 08 37 46" src="https://user-images.githubusercontent.com/2726958/61931476-f99cfa80-af80-11e9-8e5b-07bf8f6f8283.png">

If we take a look more in details and extract the content of the dSYM zip folder, we can see that `node_module`folder is included into this zip (screenshot from a remote bitrise machine):

<img width="526" alt="Screenshot 2019-07-26 at 09 33 47" src="https://user-images.githubusercontent.com/2726958/61934400-80090a80-af88-11e9-90c8-182f3be34726.png">
More than this, the source code is sent to Fabric ⚠️⚠️⚠️⚠️

That's a major issue on our side because we can't deploy on Fabric correctly, it's failing on the dSYM zip file upload. More than this, we would like to avoid to send our source code on Fabric servers...

**Comment by odemolliens** [comment]
linked to https://github.com/bitrise-steplib/steps-xcode-archive/issues/155

**Comment by lszucs** [comment]
Hi @odemolliens,

Thanks for the report! Can you please tell me which version of the step you use and whether the issue persist with the latest version?
