### ISSUE TITLE
The following build commands failed: Check dependencies

### ISSUE THREAD

**Issue by mobee-bill** [bitrise-steplib/steps-xcode-archive#161]
My builds are failing with the following:

>  Check Dependencies
    no rule to process file '/MainRewardViewController.h' of type sourcecode.c.h for architecture armv7
    no rule to process file '/MainRewardViewController.h' of type sourcecode.c.h for architecture arm64
Last lines of the Xcode's build log:
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
warning: no rule to process file '/Users/vagrant/git/Hooky/MainRewardViewController.h' of type sourcecode.c.h for architecture arm64
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
** ARCHIVE FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Archive failed, error: exit status 65

I'm not sure if this is failing due to the SWIFT_VERSION (which I do have set in my build settings to Swift 5 (am I missing something within the workflow editor?)) or if it is actually failing due to a problem with provisioning profiles. (I used the provided terminal command to export the .p12 and signing identities).  Any help appreciated. Thanks!

**Comment by ahvth-bitrise** [comment]
Hi there! 👋 Generally speaking, our forums at discuss.bitrise.io or our on-site chat would be the best place to ask a question like this which pertains to workflow configuration. Could you please as the question via one of those channels? Thanks! 😄
