### ISSUE TITLE
Question: There is a way to speed up the archive ?

### ISSUE THREAD

**Issue by sejas** [bitrise-steplib/steps-xcode-archive#162]
Do you know if there is a way to speed up the archive task?

It's spending around 31 minutes generating the archive. It would be great if you know some trick/cache to save a few minutes in this task.

Thank you !

<img width="709" alt="Captura de pantalla 2019-08-07 a las 14 34 07" src="https://user-images.githubusercontent.com/779993/62627189-cfecb780-b920-11e9-8847-efdcf9514a90.png">

**Comment by bitce** [comment]
Hi @sejas!

Generally we're recommending to turn off the `bitcode` options, in case you are not looking to send that to Apple and having Apple recompile the app based on that, that can speed up things by a significant amount.

**Comment by sejas** [comment]
Thanks for your answer ! 🤗
I will try this out.

Have a nice day !
