### ISSUE TITLE
Build script not working

### ISSUE THREAD

**Issue by CHOIMINSEOK** [bitrise-steplib/steps-xcode-archive#165]
I added script for automating update build number & app version from git tag. 
It works local build & archive, but seems not working on bitrise archive. 
Any help for me? ;l

```
# Update build version with number of commits
BUILD_NUMBER=$(git rev-list HEAD | wc -l | tr -d ' ')


# Update version string with build number
LINES_CHANGED=$(git status --porcelain | wc -l | tr -d ' ')
PLIST_CHANGED=$(git status --porcelain | grep "${INFOPLIST_FILE}" | wc -l | tr -d ' ')
if [ "$LINES_CHANGED" == "1" -a "$PLIST_CHANGED" == "1" ]; then
GIT_RELEASE_VERSION=$(git describe --tags --always)
else
GIT_RELEASE_VERSION=$(git describe --tags --always --dirty)
fi

# Update plist with new values
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${GIT_RELEASE_VERSION#*v}" "${PROJECT_DIR}/${INFOPLIST_FILE}"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${PROJECT_DIR}/${INFOPLIST_FILE}"
```

**Comment by bitce** [comment]
Hi @CHOIMINSEOK!

Could you send us an example build URL to see how the script behaves on Bitrise?

**Comment by CHOIMINSEOK** [comment]
What does build URL means? 

Here's Bitrise log file. @bitce 
[e8cf47d99704d2d1.log](https://github.com/bitrise-steplib/steps-xcode-archive/files/3573203/e8cf47d99704d2d1.log)

Thanks!

**Comment by bitce** [comment]
When we say build URL, we are referring to the URL you're on when on the builds page. It allows us to take a look at the logs and that state of the .yml so it's preferable for us, bot the log is perfectly fine, we'll take a look thanks 🙂

**Comment by bitce** [comment]
@CHOIMINSEOK can you point out where or how is this implemented during this build because I don't see the script in the logs 🤔

**Comment by CHOIMINSEOK** [comment]
▸ Compiling LogIn.storyboard
▸ Compiling Main.storyboard
▸ Compiling LaunchScreen.storyboard
▸ Processing Info.plist
**▸ Running script 'Run Script'**
▸ Generating '마인딩.app.dSYM'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Touching 마인딩.app (in target: minding-ios)
▸ Archive Succeeded

In `Xcode-Archive`step, you could find out  `Run Script`, which I added script for automating build number & app version. that is: 
```
# Update build version with number of commits
BUILD_NUMBER=$(git rev-list HEAD | wc -l | tr -d ' ')


# Update version string with build number
LINES_CHANGED=$(git status --porcelain | wc -l | tr -d ' ')
PLIST_CHANGED=$(git status --porcelain | grep "${INFOPLIST_FILE}" | wc -l | tr -d ' ')
if [ "$LINES_CHANGED" == "1" -a "$PLIST_CHANGED" == "1" ]; then
GIT_RELEASE_VERSION=$(git describe --tags --always)
else
GIT_RELEASE_VERSION=$(git describe --tags --always --dirty)
fi

# Update plist with new values
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${GIT_RELEASE_VERSION#*v}" "${PROJECT_DIR}/${INFOPLIST_FILE}"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${PROJECT_DIR}/${INFOPLIST_FILE}"
```
It works perfectly in local, but it's not in bitrise. 
I have no idea how to see detail of **▸ Running script 'Run Script'**. It would be better if I could see detailed log in that step.

**Comment by CHOIMINSEOK** [comment]
Oh, I found it! 
It was my fault. There's a small mistake in script. 
Sorry ;(

**Comment by bitce** [comment]
@CHOIMINSEOK  No worries! Happy to hear it wasn't something overly serious 🙂
