### ISSUE TITLE
Support disabling mac catalyst

### ISSUE THREAD

**Issue by abarisain** [bitrise-steplib/steps-xcode-archive#167]
Hello,

Our project supports Mac Catalyst. This requires 10.15, which Bitrise does not support yet: we have no issue with that as we're not interested in using this step to generate Catalyst builds.

Thing is, Xcode fails on 10.14 with the following:

```
❌  error: Building for Mac Catalyst requires macOS 10.15 or later. (in target 'Sample' from project 'Sample')
```

We've solved this by moving to dumb script phases that execute xcodebuild with "SUPPORTS_MACCATALYST=NO" in the arguments.

In "debug", this step allows to add extra arguments. Unfortunately they're added at the end of the command, while this needs to be a little bit earlier on. 

This is why I'd like to request support to disable mac catalyst right in the step.

**Comment by abarisain** [comment]
Scratch that, looks like just moving the argument doesn't work on a complex project (an app relying on frameworks and app extensions)

I still think it would be a nice option, but maybe it does not have its place in this

**Comment by rivera-ernesto** [comment]
I would keep this open as it will break workflows for many.

**Comment by rivera-ernesto** [comment]
Also could you better describe your BitRise workaround please?

**Comment by stgarrity** [comment]
:+1: I'm running into the same problem ... has anyone already figured out a good fix?

**Comment by rismay** [comment]
Running into the same issue.

**Comment by stgarrity** [comment]
@rismay fwiw @abarisain's solution worked for me (SUPPORTS_MACCATALYST=NO in build flags) even with frameworks, although we don't currently use extensions. Bitrise support told me it's on their list but no ETA yet :)

**Comment by abarisain** [comment]
FYI I had problems with this for some reason, and simply moved back to running a shell script calling xcodebuild

**Comment by non-binary** [comment]
Hey folks! We've released a new Stack that runs Xcode 11.4.x on macOS 10.15.3. Please don't hesitate to open a new issue if you have any problems or questions about it.

**Comment by gabors** [comment]
Hi @non-binary 

How can I build the Mac catalyst version of the iOS app in bitrise? Using the Xcode Archive & Export for iOS currently for iOS and tvOS projects.

**Comment by MapleSimon** [comment]
I was having issues with my podfile dependencies but was able to add the flag in the **Debug->Additional options for xcodebuild call** in my **Xcode Archive & Export for iOS** workflow step. FYI
![image](https://user-images.githubusercontent.com/40607756/79122990-17a4c800-7d67-11ea-8ac8-6505307d0548.png)

**Comment by non-binary** [comment]
The step's `Additional options for xcodebuild call` input can be used to pass options to the xcodebuild command call, like: `SUPPORTS_MACCATALYST=NO`.

We are aware of the issue and we have a ticket in our current sprint to resolve the issue for this step. The sprint should end Apr. 15.

We also have an investigation task in our backlog to fully revise the Catalyst support.

Setting the `SUPPORTS_MACCATALYST=NO` as `Additional options for xcodebuild call` input most likely solves the issue and the step will build the iOS part of the project

Unfortunately the mac version of the step: https://github.com/bitrise-steplib/steps-xcode-archive-mac/blob/master/step.yml has no `Additional options for xcodebuild call` input, so macOS part of the project can be built only using a custom script step

**Comment by gabors** [comment]
@non-binary Thank you so much, would really appreciate if we could automate CI for our Catalyst apps using bitrise!
If possible also consider the option to upload to Apple for notarization.

**Comment by Szabadember** [comment]
I am happy to announce that version[ 2.8.0](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/2.8.0) was released which fixes Mac Catalyst project support. We appreciate your patience and would love to hear back if this really solved your problem.

**Comment by Szabadember** [comment]
Please open a new ticket for feedback about 2.8.0 issues.
