### ISSUE TITLE
"bundle" conflicts installing fastlane

### ISSUE THREAD

**Issue by ios-dev-drivingthru** [bitrise-steplib/steps-xcode-archive#170]
Having an issue trying to upload to iTunesConnect involving a bundle conflict :

- VerboseLog: false
Setup
fastlane version defined: latest, installing...
2 attempt failed
3 attempt failed
Failed to ensure fastlane version, error: gem install command failed, output: ERROR:  Error installing fastlane:
	"bundle" from bundler conflicts with /Users/vagrant/.rbenv/versions/2.6.3/bin/bundle, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-deliver@2.16.3 (exit code: 1)         | 23.37 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...trise-steplib/steps-deploy-to-itunesconnect-deliver/issues |
| Source: .../github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver |
+---+---------------------------------------------------------------+----------+

**Comment by bitce** [comment]
Hi @ios-dev-drivingthru could you please include the related builds URL?

**Comment by vfxdrummer** [comment]
I believe that it was this one from Nov. 7th :
https://app.bitrise.io/build/3e062bed6381ebda#?tab=log

**Comment by bitce** [comment]
Hi @ios-dev-drivingthru and @vfxdrummer!

This build does not seem to contain the originally reported error and has a completely different one, can you guys please provide access to the same one? Is the issue present as we speak?
