### ISSUE TITLE
Build fails with no error message when Xcode Archive & Export for iOS

### ISSUE THREAD

**Issue by usestrive** [bitrise-steplib/steps-xcode-archive#171]
I have tried many versions and they all fail with no message or reason. 
is available in the $BITRISE_IDEDISTRIBUTION_LOGS_PATH environment variable
Export failed, error: signal: killed
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@2.4.18 (exit code: 1)   
thats all i get and the build fails

**Comment by lpusok** [comment]
Hi @usestrive,
Can you please share a build URL with support user enabled? Please also contact us on the on-site chat. Thanks!

**Comment by lpusok** [comment]
Hi @usestrive,
Can you confirm that the issue is present with a later Xcode version (stack)?

**Comment by kathrynowy** [comment]
encountered with the same issue

**Comment by bitce** [comment]
Hi @kathrynowy, please send us some details in case you experience this, like the URL of a build so we can take a look. Thanks!
