### ISSUE TITLE
issue with input CustomExportOptionsPlistContent: plist: type mismatch: tried to decode plist type `string' into value of type `map[string]interface {}'

### ISSUE THREAD

**Issue by ethanneff** [bitrise-steplib/steps-xcode-archive#174]
Why is it looking for CustomExportOptionsPlistContent?

**Comment by bitce** [comment]
Hi @ethanneff, 

Can you please send us a relevant build's URL? That would allow us to take a look at the logs 🙂

**Comment by ethanneff** [comment]
I forgot to add cocoapods and yarn to the workflow 🤕
