### ISSUE TITLE
Build fails not finding existing profile :

### ISSUE THREAD

**Issue by mfo** [bitrise-steplib/steps-xcode-archive#175]
Hello ; 

firstly very happy with your product until now. But we are facing a strange issue : 

`Code Signing Error: No profile for team 'YNE7572VMN' matching 'Bitrise ad-hoc - (city.flui.ios)' found: Xcode couldn't find any provisioning profiles matching 'YNE7572VMN/Bitrise ad-hoc - (city.flui.ios)'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor.`

Unfortunately we do have a profile matching this naming for the current team. 

Do you have any suggestion ? Do you need more log / info ?
PS: here is a build failure : url https://app.bitrise.io/build/b277de8242967406

Thanks

**Comment by mfo** [comment]
been fixed internally

**Comment by Roland-Bak** [comment]
Hey there @mfo! Happy to hear that! 
If you have some time, please feel free to share how managed to make it work, and let me know if you have any other issues :)

**Comment by anka-213** [comment]
Please, how did you solve it? 

Here's a build failure for me: https://app.bitrise.io/build/c3044105b8c00443#?tab=log
