### ISSUE TITLE
Exporting IPA from the built archive failed. Error: could not get scheme with name App from path /Users/vagrant/git/ios/App/App.xcworkspace

### ISSUE THREAD

**Issue by gerkestam2** [bitrise-steplib/steps-xcode-archive#179]
Hi,

I am facing the same issue as #173 had: right after the archive was built the bitrise build fails with the error: could not get scheme with name App from path /Users/vagrant/git/ios/App/App.xcworkspace

I am using version 2.7.1 and as development stack the latest XCode version (11.3.1).
The app itself is based on Ionic 5 + capacitor. When I open the project via capacitor (npm cap open ios) I see that the scheme 'App' is present in the workspace. Any clue what I might be missing here?

The associated bitrise URL is: https://app.bitrise.io/app/5ad5ed4782163615/workflow_editor#!/workflows?workflow_id=dev

The relevant part of the logs are:

 Compiling DefaultPlugins.m
▸ Compiling Capacitor_vers.c
▸ Compiling Capacitor-dummy.m
▸ Compiling CAPPluginMethod.m
▸ Compiling CAPPluginCall.m
▸ Compiling CAPPlugin.m
▸ Linking Capacitor
▸ Touching Capacitor.framework (in target 'Capacitor' from project 'Pods')
▸ Processing Pods-App-Info.plist
▸ Copying Pods-App-umbrella.h
▸ Compiling Pods-App-dummy.m
▸ Compiling Pods_App_vers.c
▸ Touching Pods_App.framework (in target 'Pods-App' from project 'Pods')
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Compiling AppDelegate.swift
▸ Linking App
▸ Copying /Users/vagrant/git/ios/App/public
▸ Copying /Users/vagrant/git/ios/App/App/config.xml
▸ Copying /Users/vagrant/git/ios/App/App/capacitor.config.json
▸ Compiling Main.storyboard
▸ Compiling LaunchScreen.storyboard
▸ Processing Info.plist
▸ Running script '[CP] Embed Pods Frameworks'
▸ Touching App.app (in target 'App' from project 'App')
▸ Archive Succeeded
Archive infos:
team: Recognize B.V. (SEXK4Z358N)
profile: Declaratie app TEST (ef406c70-aa3e-4727-a8f1-1ffd93356228)
export: enterprise
xcode managed profile: false
Exporting ipa from the archive...
Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: enterprise
could not get scheme with name App from path /Users/vagrant/git/ios/App/App.xcworkspace
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@2.7.1 (exit code: 1)                            | 1.7 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-xcode-archive               |
+---+---------------------------------------------------------------+----------+

**Comment by gerkestam2** [comment]
Hello,

The problem has been found. The scheme 'App' was existent in the created workspace by Capacitor. However, the scheme's container was 'App project'. When I changed the container to 'App workspace' everything worked!

**Comment by danielehrhardt** [comment]
Where did you change the container?
