### ISSUE TITLE
Build fails "Failed to parse archive, error: Info.plist not exists at: XXX.app/Info.plist"

### ISSUE THREAD

**Issue by rivera-ernesto** [bitrise-steplib/steps-xcode-archive#192]
Similar to #180, but the app doesn't have MacCatalyst enable, and has just started happening.
Stack updated to Xcode 11.5 with no luck.

Build URL https://app.bitrise.io/build/bd5ef597c921d414#?tab=log

**Comment by non-binary** [comment]
Hi @rivera-ernesto,

Please enable support access in project settings so I can access your builds.

**Comment by rivera-ernesto** [comment]
> Please enable support access in project settings so I can access your builds.

Enabled. Also note that it seems to be due to problems with XCFrameworks and CocoaPods as this happened with using the latest version of https://pspdfkit.com.

**Comment by non-binary** [comment]
Hi @rivera-ernesto,

I see you have green deploy builds now. Are you still experiencing this problem?

**Comment by rivera-ernesto** [comment]
> I see you have green deploy builds now. Are you still experiencing this problem?

Yes. I had to downgrade the problematic pod to be able to build.

**Comment by non-binary** [comment]
This sounds like it's not a Bitrise problem and more a problem with the dependency.

I'm going to close the issue but follow-up if you have any other questions

**Comment by winstondu** [comment]
@rivera-ernesto , how can I check whether a pod is problematic? Something that archives fine on my machine fails on bitrise?
