### ISSUE TITLE
2.8 Workspace + local SPM fails

### ISSUE THREAD

**Issue by jjatie** [bitrise-steplib/steps-xcode-archive#195]
Using a workspace with local SwiftPM packages consistently fails in the `showBuildSettings` command. This appears to be due to the fact that the xcproject is unaware of the local packages that the xcworkspace is aware of as running it with remote access reveals that resolving the package graph results in an unknown error.

Output from build step:
```
Failed to read project platform: /Users/vagrant/git/App.xcworkspace: failed to get target (App (DEV)) build settings: xcodebuild "-project" "/Users/vagrant/git/App/App.xcodeproj" "-target" "App (DEV)" "-configuration" "Release" "-showBuildSettings" failed: exit status 74
```

I am using a mix of of local and remote packages.

**Comment by bitce** [comment]
Hi @jjatie! Can you please include an URL to a build where this error occurs?

**Comment by jjatie** [comment]
@bitce https://app.bitrise.io/build/52b9109f44ed8215

**Comment by lpusok** [comment]
Hi @jjatie ,
What is the full output of the showBuildSettings command if you run it with Remote Access?

**Comment by jjatie** [comment]
```
vagrant@prd-atl-std-y-xcode-11-5-200715172841-5ktjcCFSHzXtEkmXxKwmjJ ~ % xcodebuild "-project" "/Users/vagrant/git/App/App.xcodeproj" "-target" "App (DEV)" "-configuration" "Release" "-showBuildSettings"
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project "/Users/vagrant/git/App/App.xcodeproj" -target "App (DEV)" -configuration Release -showBuildSettings

Resolve Package Graph

Fetching https://github.com/danielgindi/Charts

Fetching https://github.com/xmartlabs/Eureka

Fetching git@github.com:loop-software/UserDefault.git

xcodebuild: error: Could not resolve package dependencies:
  An unknown error occurred
```

The only change was removing 2 remote dependencies and replacing them with local versions. The above dependencies are all remote.

**Comment by jjatie** [comment]
@lpusok Also, changing the command to target the workspace instead works fine:
xcodebuild "-workspace" "/Users/vagrant/git/App.xcworkspace" "-workspace" "App (DEV)" "-scheme" "Release" "-showBuildSettings"

**Comment by jjatie** [comment]
The example project you posted doesn't have the package in the repo, but I noticed you added it under the `local-package` project. I've added mine to the workspace, as Xcode doesn't seem to recognize them as packages that can be built on their own (with their own schemes) when they're added under a project.

**Comment by lpusok** [comment]
What if you also add a reference of it to the project? It would be great if yo could share a project skeleton which causes this here, or by contacting the on-site support chat to figure out how can we have a look on your project.

**Comment by jjatie** [comment]
Also adding a reference in the project does not work. I have reproduce the issue here https://app.bitrise.io/app/ca8ed8d33a8da78a#

**Comment by jjatie** [comment]
It seems odd to me that the step uses workspace/scheme to archive (if the path is to a workspace), but uses the project/target to get build settings. When a workspace is provided, shouldn't it only be referring to the workspace, and vice versa if a project is provided?

**Comment by jjatie** [comment]
@lpusok Were you also able to reproduce with the sample repo?

**Comment by Robert-Bitrise** [comment]
Hi @jjatie ,

Thank you for your patience. I have seen that you already have successful builds with that workflow as you have mentioned above. Do you still notice the issue or it has been solved?

I am looking forward to your reply.

**Comment by jjatie** [comment]
Unfortunately I am still unsuccessful in using the above workflow. The successful builds are still using strictly remote packages which is impeding development a little bit.

**Comment by Robert-Bitrise** [comment]
@jjatie 
I am sad to hear that. Could you please make a separated branch which has that kind of configurations which cause a failed build? I would like to investigate that branch with your coach-adhoc-jira workflow.

**Comment by jjatie** [comment]
The branch `local-packages` has the configuration that fails. I just kicked off a build using the `coach-adhoc-jira` workflow

**Comment by arthurdapaz** [comment]
Hello. I'm facing the same issue.

Pure workspace, with a single xcode project, plus some public github swift packages and some private github swift packages

I use some Github private packages to build my project locally. My Xcode has all credentials do access my github private repos. How can we address this issue?

[**My build URL**](https://app.bitrise.io/build/6b92b06e95b72b68)

`Failed to read project platform: /Users/vagrant/git/`_redacted_`_.xcworkspace: failed to get target (`_redacted_`) build settings: xcodebuild "-project" "/Users/vagrant/git/`_redacted_`.xcodeproj" "-target" "`_redacted_`" "-configuration" "Release" "-showBuildSettings" failed: exit status 74`

**Comment by Robert-Bitrise** [comment]
@arthurdapaz Does this mean that you have solved this issue? If you do then @jjatie could you please try to do the same as @arthurdapaz did? Thank you.

Also this article could be useful: https://devcenter.bitrise.io/faq/adding-projects-with-submodules/

**Comment by jjatie** [comment]
It ended up not being the same issue. Have you investigated my comment above re: using the workspace/scheme instead of project/target commands? I'm curious to know if and why there's any objection to that.

**Comment by arthurdapaz** [comment]
> @arthurdapaz Does this mean that you have solved this issue?

Yes. It solved the problem for me.

**Comment by jjatie** [comment]
To clarify, he @arthurdapaz solved the issue they posted, but that issue was unrelated to this one.

**Comment by jjatie** [comment]
Any update on this? Any response to this:
> It seems odd to me that the step uses workspace/scheme to archive (if the path is to a workspace), but uses the project/target to get build settings. When a workspace is provided, shouldn't it only be referring to the workspace, and vice versa if a project is provided?

**Comment by Robert-Bitrise** [comment]
@jjatie 
Could you please enable again the support access? Thank you!

**Comment by jjatie** [comment]
@Robert-Bitrise enabled

**Comment by Robert-Bitrise** [comment]
@jjatie Thank you for your quick response. Did you anything on your **local-packages** branch? I ask it because currently I've tried to run your **adhoc** workflow and it has a different error message like you have earlier. Here is the latest build what I've triggered: https://app.bitrise.io/build/e5de2f0437d014f9#?tab=log

**Comment by jjatie** [comment]
No, I haven't run in it some time. I will try to update it later today. I'm still curious what your thoughts are on:
> It seems odd to me that the step uses workspace/scheme to archive (if the path is to a workspace), but uses the project/target to get build settings. When a workspace is provided, shouldn't it only be referring to the workspace, and vice versa if a project is provided?

It makes sense to me that this doesn't work — how would a project know about local dependencies declared in the workspace — and clearly the team has already identified that the workspace needs to be inspected to build a scheme. Why not inspect the workspace to get information on the scheme too?

**Comment by mjones-droid** [comment]
Hey @jjatie! Robert is out of the office so I'm following up on his tickets while he's out. 

I get what you're saying, but that's not the way Bitrise works. Build settings are pulled from the project. As to the rationale of why it's done that way, I can't speak to this. 

It looks like its been a while since the last update. Are you still experiencing issues? If so, it looks like your support access has expired so I'd appreciate it if you'd turn it back on. Also, please send a recent build with the problem. 

Matthew
Senior Customer Engineer

**Comment by jjatie** [comment]
I'm not sure what you mean by:
> but that's not the way Bitrise works

[This Bitrise step](https://github.com/bitrise-steplib/steps-xcode-archive) works that way.

It is still an issue. I will try to prepare a build to reproduce shortly

**Comment by sl-benjaminpayen** [comment]
We have the same problem with one of our projects, and downgrade to the 2.7 version seems to fix the problem...
