### ISSUE TITLE
Build Fails: "Failed to open project - could not get scheme - failed to unmarshal scheme file"

### ISSUE THREAD

**Issue by zarghol** [bitrise-steplib/steps-xcode-archive#196]
Hi, I am getting this error every time I try to deliver the app.
The unit tests works so It is not a problem of build itself.

Here is the log : 

```
- ExportMethod: enterprise
- UploadBitcode: false
- CompileBitcode: false
- ICloudContainerEnvironment: 
- TeamID: 
- UseDeprecatedExport: false
- ForceTeamID: 
- ForceProvisioningProfileSpecifier: 
- ForceProvisioningProfile: 
- ForceCodeSignIdentity: 
- CustomExportOptionsPlistContent: 
- OutputTool: xcpretty
- Workdir: /Users/vagrant/git
- ProjectPath: XXXXX.xcworkspace
- Scheme: YYYYY
- Configuration: XXXXX
- OutputDir: /Users/vagrant/deploy
- IsCleanBuild: false
- XcodebuildOptions: 
- DisableIndexWhileBuilding: true
- ExportAllDsyms: true
- ArtifactName: XXXXXX
- VerboseLog: true
- CacheLevel: swift_packages
step determined configs:
- xcodebuildVersion: Xcode 11.3.1 (Build version 11C504)
Checking if output tool (xcpretty) is installed
- xcprettyVersion: 0.3.0
Failed to open project: /Users/vagrant/git/XXXXX.xcworkspace: could not get scheme (YYYYY) from path (/Users/vagrant/git/XXXXX.xcworkspace): failed to unmarshal scheme file: /Users/vagrant/git/CR/Core.xcodeproj/xcshareddata/xcschemes/CoreTests.xcscheme, error: EOF
```

I don't understand why It tries to open Core.xcodeproj, that is used in the project, but not the app workspace.
I inspected the scheme and it is well placed at  `/Users/vagrant/git/XXXXX.xcworkspace/xcshareddata/xcschemes/YYYYY.xcscheme`

The Bitrise support mode is enabled and here is the link to the log : https://app.bitrise.io/build/c28e5f0d2e63fd5d#?tab=log

**Comment by non-binary** [comment]
Hi @zarghol,

I believe the problem is the spaces in your scheme name. Please try removing them.

**Comment by zarghol** [comment]
Hi, thanks I'll try this

**Comment by zarghol** [comment]
Still the same error : https://app.bitrise.io/build/08c76b0f5a46e818#?tab=log

**Comment by bitce** [comment]
Hi @zarghol!

Sorry about the silence until now. Can you advise if the issue is still present? We're seeing a lot of successful build on the same workflow, which is hopefully good news!

**Comment by zarghol** [comment]
Hello ! Yes that's good for now. It appears I had an empty xcscheme file in the workspace that drove to this issue. I removed it and it works now

**Comment by MayoudP** [comment]
> Hello ! Yes that's good for now. It appears I had an empty xcscheme file in the workspace that drove to this issue. I removed it and it works now

I don't have any empty xcsheme but still got the same issue, can you develop what you did ? You had a full empty file . xcscheme, which one ?

**Comment by bitce** [comment]
Hi @MayoudP, please include a build URL if you're experiencing an issue so we can take a look!

**Comment by jlstr** [comment]
@zarghol Hello there, Could you please elaborate on how you solved it? Thank you.

**Comment by zarghol** [comment]
At the file path mentioned by the error, I had a xcscheme file, but it was empty. So I deleted it, and it worked. I don't remember if after the first working pipeline, I recreated a new scheme in Xcode to replace it, or just deleted it.

**Comment by chaitanyatanna-bitrise** [comment]
Thank you @zarghol for the solution.

Thanks
Chaitanya

**Comment by jlstr** [comment]
Yes, thank you @zarghol! In my case it was something similar, my xcscheme file name had trailing space! once I removed it and pushed it to github, it started to work just fine.
