### ISSUE TITLE
The following build commands failed: CompileSwift normal arm64

### ISSUE THREAD

**Issue by zombieleet** [bitrise-steplib/steps-xcode-archive#206]
I am currently having this error in the xcode-archive stage,

```
** ARCHIVE FAILED **
The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
```

This is the location of my build logs [build logs](https://app.bitrise.io/build/3d7c67b9c1eb1649#?tab=log)

I have tried curbing the internet for the possible cause of this, but I could not get to the root cause as I am new to IOS development. Please let me know if I can provide any more files to help solve this

**Comment by non-binary** [comment]
Hi @zombieleet,

Can you please enable support access in your project's settings so we can access your builds?

**Comment by zombieleet** [comment]
I have fixed this already. Thanks :)

**Comment by non-binary** [comment]
Awesome, that's great to hear! Do you mind sharing what you did so future passerbyers can fix their issue?

**Comment by zombieleet** [comment]
@non-binary I had to remove cordova-plugin-firebase-analytics it was conflicting with capacitor-firebase-analytics
