### ISSUE TITLE
Archive failed, error: exit status 65

### ISSUE THREAD

**Issue by praneeth-hiver** [bitrise-steplib/steps-xcode-archive#207]
❌  /Users/vagrant/git/packages/app/node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m:212:18: property 'allowedScrollTypesMask' not found on object of type 'RNBetterPanGestureRecognizer *'
      recognizer.allowedScrollTypesMask = UIScrollTypeMaskAll;
                                                          ^
❌  /Users/vagrant/git/packages/app/node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m:212:43: use of undeclared identifier 'UIScrollTypeMaskAll'
      recognizer.allowedScrollTypesMask = UIScrollTypeMaskAll;
                 ^

LOG FILE: 
[8697652b5648d459.log](https://github.com/bitrise-steplib/steps-xcode-archive/files/5595367/8697652b5648d459.log)

**Comment by praneeth-hiver** [comment]
Working fine with the same workflow 6 days back

**Comment by non-binary** [comment]
Hi @praneeth-hiver,

Can you please send a link to a build and enable support access?

**Comment by praneeth-hiver** [comment]
> enable support access

https://app.bitrise.io/build/1f3b1a5349a6161b#?tab=log
I have enabled support access as well. 
Thank you. @non-binary

**Comment by bitce** [comment]
Hi @praneeth-hiver,

Have you made sure changes between commits didn't cause this change? The error message 

```
x /Users/vagrant/git/packages/app/node_modules/react-native-gesture-handler/ios/Handlers/RNPanHandler.m:212:43: use of undeclared identifier 'UIScrollTypeMaskAll'
recognizer.allowedScrollTypesMask = UIScrollTypeMaskAll;
```

For instance suggest that `'UIScrollTypeMaskAll' ` is not included in the `RNPanHandler` class. We'd recommend looking at that and `RNGestureHandler.h ` initially, if all looks well, you could try to debug this locally, we have guide about that here: https://blog.bitrise.io/how-to-debug-your-build-locally

Hope this helps!

**Comment by girish-grexit** [comment]
@praneeth-hiver @bitce After debugging we found that the issue is due to the X-Code version which we are using in the bitrise. allowedScrollTypesMask is added in iOS 13.4+ and for that X-code 11.4 and above is required.

**Comment by praneeth-hiver** [comment]
That's great news, we know what the issue is now, we can update our
workflow settings and go from there.

Thanks @Bitrise <builds+af2c4f4af9764541@bitrise.io>
cc @Girish Kumar <girish@grexit.com>
