### ISSUE TITLE
Failed to open project: /Users/vagrant/git/ZZZ.xcworkspace: could not get scheme (XXX) from path (/Users/vagrant/git/ZZZ.xcworkspace): scheme XXX not found in ZZZ

### ISSUE THREAD

**Issue by jlstr** [bitrise-steplib/steps-xcode-archive#214]
Hello there, I'm getting the following error, when I try to build a different Scheme.

```
+------------------------------------------------------------------------------+

| (6) xcode-archive@2                                                          |
+------------------------------------------------------------------------------+
| id: xcode-archive                                                            |
| version: 2.8.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-01-14T16:04:30Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[16:04:31]  * [OK] Step dependency (xcode) installed, available. 
Configs:
- ExportMethod: app-store
- UploadBitcode: true
- CompileBitcode: true
- ICloudContainerEnvironment: 
- TeamID: 
- UseDeprecatedExport: false
- ForceTeamID: 
- ForceProvisioningProfileSpecifier: 
- ForceProvisioningProfile: 
- ForceCodeSignIdentity: 
- CustomExportOptionsPlistContent: 
- OutputTool: xcpretty
- Workdir: /Users/vagrant/git
- ProjectPath: ZZZ.xcworkspace
- Scheme: XXX
- Configuration: 
- OutputDir: /Users/vagrant/deploy
- IsCleanBuild: false
- XcodebuildOptions: 
- DisableIndexWhileBuilding: true
- ExportAllDsyms: true
- ArtifactName: XXX
- VerboseLog: true
- CacheLevel: swift_packages
step determined configs:
- xcodebuildVersion: Xcode 12.2 (Build version 12B45b)
Checking if output tool (xcpretty) is installed
- xcprettyVersion: 0.3.0
Failed to open project: /Users/vagrant/git/ZZZ.xcworkspace: could not get scheme (XXX) from path (/Users/vagrant/git/ZZZ.xcworkspace): scheme XXX not found in ZZZ
```
I also added an Script to the Workflow that prints the Shared Schemes available:
`xcodebuild -workspace $BITRISE_PROJECT_PATH -list`

And I can confirm the Scheme gets printed when the Scheme runs. Could you please help me out with this issue?

**Comment by luna-kx** [comment]
Hi @jlstr,

Can you please send over a link to a build and enable support access?

**Comment by jlstr** [comment]
Howdy @luna-kx,

Big update, I've been able to resolve this issue. The problem was that for some reason the xcscheme file had a trailing space. ie. `MY SCHEME NAME .xcscheme`, once I removed the trailing space and pushed to github, it started to work. And even before doing that, I changed the ENV VAR for that scheme, added the trailing space and then it also worked.

Since you're on the line, may I ask you this instead, I have two versions of an App, one for Production, one for Staging, they have different bundle IDs obviously, as you know Apple has a limit on distribution certificates, the question is: Can I safely use a Distribution Certificate with the **Wild Card** * bundle ID for both Apps?

Thank you!

**Comment by luna-kx** [comment]
Hi @jlstr,

That's awesome! I'm glad to hear you were able to figure it out.

You should be able to use the wildcard certificate. In this case you have define the bundle ID in a special format for example `com.bitrise.*`. With this you will be able to code sign any of your apps which has com.bitrise. as a prefix in its bundle ID. 

There are some restrictions for Wildcards, for example you can use Push notifications on your app because that requires unique bundle ID

Please let me know if this helps!

**Comment by bazuka5801** [comment]
@jlstr XCode -> Product -> Scheme -> Manage Schemes -> Re-Click "XXX" Scheme
