### ISSUE TITLE
[iOS] Failed to parse archive, error: Info.plist not exists at: 

### ISSUE THREAD

**Issue by tr3v3r** [bitrise-steplib/steps-xcode-archive#219]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.2.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NO

### Issue description

Step fails after Archive Success with error: 
```
Failed to parse archive, error: Info.plist not exists at: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__archive__620951398/***.xcarchive/Info.plist
```

Running archive locally doesn't produce any errors.

### Bitrise info

- Build URL: https://app.bitrise.io/build/be1860a7f0621e78#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES
- Log: 

<details>
  <pre>
▸ Archive Succeeded
Failed to parse archive, error: Info.plist not exists at: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__archive__620951398/***.xcarchive/Info.plist
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@3 (exit code: 1)                                | 25.1 min |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-xcode-archive               |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

**Comment by lucasfronza** [comment]
We are having the same issue.
Build URL: https://app.bitrise.io/build/72445c3a38febbe0#?tab=log

For a bit more context, ours is a React Native app and this started happening after we upgraded from 0.63 to 0.64. Also, we tested on step versions 3.1 and 3.2 and it happens on both.

**Comment by lucasfronza** [comment]
Not sure what the fix, but I think I've found the probable cause.

> ls -al /var/folders/r5/krgx70l166396y7gv0tvwfpm0000gn/T/__archive__935362440/***.xcarchive/

With CocoaPods 1.9.3:
```
drwxr-xr-x  7 username  staff  224 23 Mar 11:44 BCSymbolMaps
-rw-r--r--  1 username  staff  958 23 Mar 11:44 Info.plist
drwxr-xr-x@ 3 username  staff   96 23 Mar 11:41 Products
drwxr-xr-x  3 username  staff   96 23 Mar 11:44 SwiftSupport
drwxr-xr-x  5 username  staff  160 23 Mar 11:44 dSYMs
```

With CocoaPods 1.10.1
```
drwxr-xr-x  7 username  staff  224 23 Mar 10:27 BCSymbolMaps
drwxr-xr-x@ 3 username  staff   96 23 Mar 10:23 Products
drwxr-xr-x  5 username  staff  160 23 Mar 10:27 dSYMs
```

---

React Native 0.64 requires CocoaPods 1.10

**Comment by tr3v3r** [comment]
@lucasfronza Thanks! The problem was with the Mapbox pod. We can close the issue

**Comment by lucasfronza** [comment]
Yep, our Mapbox version is not compatible with 1.10.1. Testing the latest Mapbox version at this moment to make sure that is it, but it seems like it is 👍

**Comment by tr3v3r** [comment]
@lucasfronza actually I've updated to the latest beta version - and issue is gone ;)

**Comment by winstondu** [comment]
We are having this with a particular cocoapod. Not sure what the solution should be here...

**Comment by Roland-Bak** [comment]
Hi there @winstondu 👋

Could you please share your build URL with Support Access enabled? 🙂

**Comment by DaNiELChIoRo-backbase** [comment]
Facing same issue with native app, suddenly stop working as expected. Any advice?

**Comment by Roland-Bak** [comment]
Hello @DaNiELChIoRo-backbase 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by DaNiELChIoRo-backbase** [comment]
We already solve out the problema, turns out it was an Xcode configuration

**Comment by DaNiELChIoRo-backbase** [comment]
Update, we tacked down the issue, turns out that the problem were on the Xcode configuration itself! When we tried to archive locally it turns out to be a wrong update configuration with linked libraries on the unit testing building settings which it was perform in order to make unit tests work for Xcode 12.4 version but broke the archive without us noticing it! Once this was remove it worked again smooth as before

**Comment by mefiblogger** [comment]
Hello There, 👋

Thanks for updating the issue, I'm happy that it has resolved now.

I'm going to close this one down, but please feel free to open a new issue if there's any trouble.

Happy Building 🚀
Mefi from Bitrise
