### ISSUE TITLE
[iOS] Build fails: Failed to open project: /Users/vagrant/git/MyProject.xcworkspace: No file found at path: /Users/vagrant/git/My_Project.xcodeproj/project.pbxproj

### ISSUE THREAD

**Issue by Daniebro5** [bitrise-steplib/steps-xcode-archive#222]
I’m trying to get a build for iOS using the Xcode export Archive but I’m getting Failed to open project: /Users/vagrant/git/MyProject.xcworkspace: No file found at path: /Users/vagrant/git/My_Project.xcodeproj/project.pbxproj

Notice the underscore ( _ ) between words.

It fails at the Xcode Archive & Export for iOS no matter the version

**Comment by Roland-Bak** [comment]
Hi there @Daniebro5 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) so that we can take a more in-depth look? 🙂
