### ISSUE TITLE
iOS - Using xcframework embedded returns - is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by fabriciomasiero** [bitrise-steplib/steps-xcode-archive#225]
/Users/vagrant/git/Shared/View/ContentView.swift:30:20: cannot find type 'Station' in scope
    let stations: [Station]

# Bitrise Build Issue Report template

## Description of the issue

I have been trying to build my project in Swift using Xcode with an xcframework inside the bitrise but I have been encountering problems.

After configuring my workflows, when compiling I get some errors like: is unavailable: cannot find Swift declaration for this class - From the files that are inside my xcframework.

When running the bitrise on my local machine, everything worked perfectly.

## Environment:

Works fine on my MacBook, I'm using bitrise CLI, and works well.

Do not work on bitrise.io

__Which build Step causes the issue and which version of the step?__

Xcode Archive & Export for iOS v3.2.x

## Reproducibility

Just let it build and when goes through Xcode Archive I received the error

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](http://devcenter.bitrise.io/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _Does the issue happen sporadically, or every time?_ : YES
- _Does upgrading the build Step to the latest version help?_ : NO
- _When did the issue start?_ : Always happened

### Local reproduction

If I run it locally, works perfectly 

## Build log

https://app.bitrise.io/build/41f74f89fe19d9a2#?tab=log

**Comment by Roland-Bak** [comment]
Hello @fabriciomasiero 👋

Have you tried rebuilding in a clean git environment?
Please follow these steps: 

1. open your Terminal / Command Line
2. type in: cd /tmp
3. clone your repository with: git clone REPOURL ./quick-repo-test --branch BRANCH-YOU-WANT-TO-TEST
4. example: git clone https://github.com/bitrise-io/bitrise.git ./quick-repo-test --branch master
5. cd ./quick-repo-test

If this is done and it works without issues, please send us the results 🙂
