### ISSUE TITLE
Deploy artificatory failing

### ISSUE THREAD

**Issue by pavm035** [bitrise-steplib/steps-xcode-archive#228]
Hi,

Not sure if it's issue of `steps-deploy-to-bitrise-io` plugin, but here is the detail bug report
https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/140

**Comment by godrei** [comment]
Hi @pavm035 ,
sorry for the inconvenience, you can read more about the issue in the related PR description: https://github.com/bitrise-steplib/steps-xcode-archive/pull/229.
The changes released in version [3.2.4](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/3.2.4).
