### ISSUE TITLE
Version 3.2.4 Broke Additional options for xcodebuild call step

### ISSUE THREAD

**Issue by Bunn** [bitrise-steplib/steps-xcode-archive#231]
### Troubleshooting

On the `Additional options for xcodebuild call` step I have the following parameters:
APP_PROFILE="$APP_PROFILE" EXTENSION_PROFILE="$EXTENSION_PROFILE"

This used to work great on version 3.2.2, generating this output:
```
| id: xcode-archive                                                            |
| version: 3.2.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-05-30T16:46:19+01:00        

[16:46:34] $ set -o pipefail && xcodebuild "-workspace" "/Users/vagrant/git/ios/XXX.xcworkspace" "-scheme" "XXX" "DEVELOPMENT_TEAM=XXX" "CODE_SIGN_IDENTITY=XXX" "COMPILER_INDEX_STORE_ENABLE=NO" "archive" "-archivePath" "/var/folders/wp/4pf4qdmn217djs68lskdcc780000gn/T/__archive__088100788/XXX.xcarchive" "-destination" "generic/platform=iOS" "APP_PROFILE=XXX" "EXTENSION_PROFILE=XXX" | xcpretty
### Useful information
```

But now, on version 3.2.4, it doesn't work anymore:
```
| id: xcode-archive                                                            |
| version: 3.2.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-06-03T12:42:17Z              

[12:58:44] set -o pipefail && xcodebuild "-exportArchive" "-archivePath" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/xcodeArchive902148157/XXX.xcarchive" "-exportPath" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/xcodeIPAExport054201464/exported" "-exportOptionsPlist" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/xcodeIPAExport054201464/export_options.plist" | xcpretty
```

You can see that there's a lot of parameters missing now:
CODE_SIGN_IDENTITY, APP_PROFILE, EXTENSION_PROFILE

This causes the build to fail because Xcode can't properly sign the builds.
Ideally minor patch versions (from 3.2.2 to 3.2.4) should not change behavior, specially in a breaking way. Unfortunately this is causing a big disruption at the company I work for which uses Bitrise as a CD system.

Thank you for taking the time and looking into this. Please let me know if extra info is required.

### Bitrise info

Build that doesn't work:
https://app.bitrise.io/build/b11a15c805565828#?tab=log

Build that worked:
https://app.bitrise.io/build/ac829f842871ad1d#?tab=log

**Comment by godrei** [comment]
HI @Bunn ,
sorry for the inconvenience!

Based on your build log:
line 1137: `[0m- ExportMethod: auto-detect`
line 20044-20068:
```
generated export options content:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
	</dict>
</plist> <nil>
...
```

This is issue seems to be related to the `ExportMethod: auto-detect` Input, you can read more about the issue and the fix here: https://github.com/bitrise-steplib/steps-xcode-archive/pull/232.

The latest version ([3.2.5](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/3.2.5)) fixes the problem, I'll close this issue, but if you need more info/help just let us know by opening a new one!
