### ISSUE TITLE
dSYM files missing from the zip folder

### ISSUE THREAD

**Issue by Christian-Truemper** [bitrise-steplib/steps-xcode-archive#236]
Hello everybody,

in the current version 3.2.5 is a bug in the export script for the archive dSYM files. 
In the dSYM zip folder all some dSYM files from the archive -> dSYMs folder are missing.

See the screenshots:

dSYM zip folder:

<img width="668" alt="Bildschirmfoto 2021-06-16 um 09 38 28" src="https://user-images.githubusercontent.com/55839117/122178468-e8b44580-ce86-11eb-9e81-ba0056503fbd.png">

Archive dSYMs folder:

<img width="857" alt="Bildschirmfoto 2021-06-16 um 09 41 41" src="https://user-images.githubusercontent.com/55839117/122178844-3f218400-ce87-11eb-8ac8-ad66e7e9da65.png">

**Comment by Roland-Bak** [comment]
Hi there @Christian-Truemper 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by Christian-Truemper** [comment]
Hi @Roland-Bak,

the Support Access on the Settings tab is enabled.
Can I send you the log file through private or support channels? 🙂

Thanks.

**Comment by Roland-Bak** [comment]
Hey there @Christian-Truemper 👋

You can send the info on https://support.bitrise.io/hc/en-us, which creates a ticket with us, and is the official support channel we can investigate on 🙂
