### ISSUE TITLE
Auto Provisioning + Manual isn't working

### ISSUE THREAD

**Issue by mvorisis** [bitrise-steplib/steps-xcode-archive#239]
### Troubleshooting

I tried to put allowProvisioningUpdates like this but it didn't work (I couldn't find somewhere the correct format)

- xcode-archive@3:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - compile_bitcode: 'no'
        - configuration: Debug
        - upload_bitcode: 'no'
        - xcodebuild_options: "- xcodebuild_options: -allowProvisioningUpdates"
        - export_method: "$BITRISE_EXPORT_METHOD"

### Issue description

In my project I have 2 targets, one is my main project and the other is an extension of previous target. In my main project I have to set manual provisioning profile, but I don't want manual in my extension, so this is the error I get:

❌  error: No profiles for 'my-target-bundle' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'my-target-bundle'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'my extension target' from project 'main target')

### Bitrise info

I use the latest version (3.3.0)

**Comment by thinguyenbit** [comment]
> ### Troubleshooting
> I tried to put allowProvisioningUpdates like this but it didn't work (I couldn't find somewhere the correct format)
> 
> * xcode-archive@3:
>   inputs:
>   - project_path: "$BITRISE_PROJECT_PATH"
>   - scheme: "$BITRISE_SCHEME"
>   - compile_bitcode: 'no'
>   - configuration: Debug
>   - upload_bitcode: 'no'
>   - xcodebuild_options: "- xcodebuild_options: -allowProvisioningUpdates"
>   - export_method: "$BITRISE_EXPORT_METHOD"
> 
> ### Issue description
> In my project I have 2 targets, one is my main project and the other is an extension of previous target. In my main project I have to set manual provisioning profile, but I don't want manual in my extension, so this is the error I get:
> 
> ❌ error: No profiles for 'my-target-bundle' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'my-target-bundle'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'my extension target' from project 'main target')
> 
> ### Bitrise info
> I use the latest version (3.3.0)

Can you please supply us with a build URL and enable support access?

Thank you

**Comment by mvorisis** [comment]
@thinguyenbit Thank you for your answer, I have enabled support access can you tell me how can i share the build url? I assume it isnt the link of failed build right?

**Comment by thinguyenbit** [comment]
You can find the build URL at the top of your build page, it should look something like:

https://app.bitrise.io/build/c292426f-7033-456f-d#?tab=log

Thi

**Comment by mvorisis** [comment]
Hi 

This is the url with the issue I describe 
https://app.bitrise.io/build/40445772-475f-475d-bd07-195dcc8d463d#?tab=log

**Comment by thinguyenbit** [comment]
Hello!

It looks like the uploaded profiles does not match the project you are working on:

❌  error: No profiles for 'com.efg.Eurobank.Eurobank-Mobile-SiriUI' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.efg.Eurobank.Eurobank-Mobile-SiriUI'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Eurobank Mobile SiriUI' from project 'Eurobank Mobile iOS')
❌  error: No profiles for 'com.efg.Eurobank.Eurobank-Mobile-Siri' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.efg.Eurobank.Eurobank-Mobile-Siri'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Eurobank Mobile Siri' from project 'Eurobank Mobile iOS')

Have you tried to use iOS Auto Provision?

https://devcenter.bitrise.io/code-signing/ios-code-signing/ios-auto-provisioning/#configuring-ios-auto-provisioning

This step would help generate the correct profiles based on the certificates added

Thi

**Comment by mvorisis** [comment]
@thinguyenbit  thank you for the edit if you can delete the reply as its still shown from edited history.

I opened a ticket and this is where we up to:

I don't have to put anything in the generic storage but make a secret value with my certificates but I don't know the format I should put and every try is failing

This is my secret value now (with a dummy name now)
<img width="1364" alt="Screenshot 2021-07-13 at 7 02 19 PM" src="https://user-images.githubusercontent.com/18750097/125485968-5ab613c5-2fcb-448f-9dc8-efe39546e939.png">

**Comment by thinguyenbit** [comment]
Sorry about that! 

What is the ticket number?

Thi

**Comment by mvorisis** [comment]
The ticket number is 17348 
Thank you

**Comment by thinguyenbit** [comment]
It looks like you are already working with Bence, so I will let you continue your conversation there.

Thank you,

Thi

**Comment by mvorisis** [comment]
For anyone who check this issue here is what you have to do:

First of all upload all of your provisioning profiles (ad-hoc development appstore enterprise, if you will use one you can upload just one) in code signing section (you don't need anything in generic file storage).

Then add only one certificate and profile installer step and **don't change** anything.

Finally in Xcode Archive & Export for iOS step you have to navigate in Debug section and add a value in Custom export options plist content (this can be found when you archive and export an ipa locally in your machine by opening ExportOptions.plist file).

This is a sample of the value you will have to put:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>destination</key>
	<string>export</string>
	<key>method</key>
	<string>app-store</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>bundleID</key>
		<string>bundleID-provisioning profile</string>
		<key>target-bundleID</key>
		<string>target-bundleID-provisioning profile</string>
		<key>target2-bundleID</key>
		<string>target2-bundleID-provisioning profile</string>
	</dict>
	<key>signingCertificate</key>
	<string>Apple Distribution</string>
	<key>signingStyle</key>
	<string>manual</string>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>yourTeamID</string>
	<key>uploadBitcode</key>
	<true/>
	<key>uploadSymbols</key>
	<true/>
</dict>
</plist>`
