### ISSUE TITLE
dsyms are no longer there

### ISSUE THREAD

**Issue by dbilgin** [bitrise-steplib/steps-xcode-archive#241]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.3.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description
On Friday everything was fine, today we get the message `no app dsyms found` during our build and then when I looked inside `BITRISE_DSYM_DIR_PATH ` it was indeed empty.

**Comment by ofalvai** [comment]
Hello @dbilgin 👋 

Can you confirm that if you roll back to [step version 3.3.0](https://github.com/bitrise-steplib/steps-xcode-archive/releases) the issue disappears?

**Comment by dbilgin** [comment]
Hey @ofalvai, thanks for getting back so fast, I just tried 3.3.0 and everything worked fine

**Comment by dbilgin** [comment]
@ofalvai We use react native, if that helps

**Comment by ofalvai** [comment]
Hey @dbilgin, we released a fix in version 3.3.2, please upgrade your workflows and let us know about the results!

**Comment by dbilgin** [comment]
@ofalvai just tried it out and it works, thank you for the fix!
