### ISSUE TITLE
Invalid bitcode version (Producer: '1300.0.29.3.0_0' Reader: '1205.0.22.11_0') issue 

### ISSUE THREAD

**Issue by j-won-o** [bitrise-steplib/steps-xcode-archive#249]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES / NO
- Does the issue happen sporadically, or every time? SPORADIC / EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL:  https://app.bitrise.io/build/6b7e6831-af8f-4696-8dd4-99ee2df02ef6#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log:

<details>
  <pre>

❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1300.0.29.3.0_0' Reader: '1205.0.22.11_0')', using libLTO version 'LLVM version 12.0.5, (clang-1205.0.22.11)' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

  </pre>
</details>

### Steps to reproduce

Archive failed because there is two different xcode version on the machine.

https://stackoverflow.com/a/55410477/8813422

**Comment by ofalvai** [comment]
Hey @j-won-o 👋 

Are you still experiencing the issue? We deployed some updates to our build VMs in the last few weeks, I believe this was fixed.

**Comment by BigPun86** [comment]
updated from 3.3.2 to 4.0.4 and still having this issue. are there any insights on how to fix this?

**Comment by gabrieldonadel** [comment]
I've just faced this issue as well, any fix for this?

**Comment by BigPun86** [comment]
it worked when updating the Xcode stack to v12.5

**Comment by mifi** [comment]
FWIW having the same issue on appcenter.ms with xcode 12.5.1. trying xcode 13 now...
