### ISSUE TITLE
archive action not defined for scheme

### ISSUE THREAD

**Issue by crisari666** [bitrise-steplib/steps-xcode-archive#280]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.2
- Is the issue reproducible with the latest version? NO
- Does the issue happen sporadically, or every time? EVERY TIME

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

failed to find build project: archive action not defined for scheme: Cinemark Production
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@4.2 (exit code: 1)                              | 18.01 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-xcode-archive               |
+---+---------------------------------------------------------------+----------+

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/84755a3d-0b41-4fcf-bc82-acd1706402c5#?tab=log)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
Installing cybersource-ios-sdk (1.0.3)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing leveldb-library (1.22)
Installing nanopb (1.30905.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 10 dependencies from the Podfile and 28 total pods installed.
[!] Automatically assigning platform `iOS` with version `9.0` on target `Cinemark Prod` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
[!] Automatically assigning platform `iOS` with version `9.0` on target `Cinemark Dev` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
Collecting Pod cache paths...
Success!
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | cocoapods-install@2                                           | 6.6 min  |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (6) xcode-archive@4.2                                                        |
+------------------------------------------------------------------------------+
| id: xcode-archive                                                            |
| version: 4.2.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2022-02-04T15:17:04Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[15:17:04]  * [OK] Step dependency (xcode) installed, available. 
Inputs:
- distribution_method: app-store
- upload_bitcode: true
- compile_bitcode: true
- icloud_container_environment: <unset>
- export_development_team: <unset>
- export_options_plist_content: <unset>
- log_formatter: xcpretty
- project_path: Cinemark/Cinemark.xcworkspace
- scheme: Cinemark Production
- configuration: <unset>
- output_dir: /Users/[REDACTED]/deploy
- perform_clean_action: false
- xcodebuild_options: <unset>
- xcconfig_content: COMPILER_INDEX_STORE_ENABLE = NO
- export_all_dsyms: true
- artifact_name: <unset>
- verbose_log: false
- cache_level: swift_packages
- automatic_code_signing: apple-id
- certificate_url_list: [REDACTED]
- passphrase_list: *****
- keychain_path: /Users/[REDACTED]/Library/Keychains/login.keychain
- keychain_password: *****
- register_test_devices: false
- min_profile_validity: 0
- BITRISE_BUILD_URL: https://app.bitrise.io/build/84755a3d-0b41-4fcf-bc82-acd1706402c5
- BITRISE_BUILD_API_TOKEN: *****
Xcode version:
Xcode 12.5.1 (Build version 12E507)
Fetching Apple Service connection
Bitrise Apple Developer Connection with Apple ID found.
Using Apple Service connection with Apple ID.
failed to find build project: archive action not defined for scheme: Cinemark Production
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@4.2 (exit code: 1)                              | 18.01 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-xcode-archive               |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (7) deploy-to-itunesconnect-application-loader@1                             |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| - | deploy-to-itunesconnect-application-loader@1                  | 1.75 sec |
+---+---------------------------------------------------------------+----------+
+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | activate-ssh-key@4                                            | 8.89 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone@6                                                   | 1.1 min  |
+---+---------------------------------------------------------------+----------+
| ! | cache-pull@2 (exit code: 1)                                   | 3.80 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-cache-pull/issues    |
| Source: https://github.com/bitrise-steplib/steps-cache-pull.git              |
+---+---------------------------------------------------------------+----------+
| ✓ | Do anything with Script step                                  | 1.98 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | certificate-and-profile-installer@1                           | 7.20 sec |
+---+---------------------------------------------------------------+----------+
| ✓ | cocoapods-install@2                                           | 6.6 min  |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@4.2 (exit code: 1)                              | 18.01 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-archive/issues |
| Source: https://github.com/bitrise-steplib/steps-xcode-archive               |
+---+---------------------------------------------------------------+----------+
| - | deploy-to-itunesconnect-application-loader@1                  | 1.75 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 8.4 min                                                       |
+------------------------------------------------------------------------------+
Submitting anonymized usage information...
For more information visit:
https://github.com/bitrise-io/bitrise-plugins-analytics/blob/master/README.md
Bitrise build failed (exit code: 1)
exit status 1
  </pre>
</details>

### Steps to reproduce

1. create pull request
2. Bitrise run workflow

**Comment by lpusok** [comment]
Hello @crisari666,
Did you manage to solve the issue?
