### ISSUE TITLE
Can't find Provision Profile

### ISSUE THREAD

**Issue by lzagar-comi** [bitrise-steplib/steps-xcode-archive#283]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.x.x
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time?  EVERY TIME

### Bitrise info

- Log: Certificate and profile installer

<details>
  <pre>
 Provision Profile (xxx-xxx-xxx-xxxxad87)
...
  </pre>
</details>

- Log: Xcode Archive & Export for iOS

<details>
  <pre>
 error: No profiles for 'xxx.xxx.xxx' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'xxx.xxx.xxx'
  </pre>
</details>

### Steps to reproduce

1. Update Provisioning Profile
2. Remove old Provisioning Profile
3. Add new Provisioning Profile to Code Sign
4. Start build
5. Certificate and profile installer -> downloads correct profile
6. Xcode Archive & Export for iOS -> No profiles for 'xxx.xxx.xxx' were found

**Comment by lpusok** [comment]
Can you please turn on verbose logs for the xcode-archive Step and share the full build log (with secrets omitted)?

**Comment by lpusok** [comment]
Hello Luka @lzagar-comi ,
Did you manage to solve the issue?
