### ISSUE TITLE
failed to manage code signing.... failed to unmarshal response: parsing time

### ISSUE THREAD

**Issue by mthompson-spectra** [bitrise-steplib/steps-xcode-archive#288]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.3.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? UNKNOWN

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

On trying to setup automatic code signing (apple-id), I am getting the attached parse error. It appears that the request to get profile info from my apple account is working but the xcode-archive step is failing to parse the (expiry?) timestamp because of a formatting mismatch. 

### Bitrise info

- Build URL: https://app.bitrise.io/build/a3b62964-cd14-45d3-b706-bf3c2b50cc20
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
Checking development provisioning profiles
Using certificate for development distribution: Apple Development: XXXXXXXXXXXXX
  Checking bundle id: xxx.yyy.zzz
  capabilities:
Exporting outputs...
failed to manage code signing: failed to ensure profiles: failed to find profile: failed to unmarshal response: parsing time ""2023-03-23 20:22:41 UTC"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 20:22:41 UTC"" as "T"
  </pre>
</details>

### Steps to reproduce

1. Enable xcode-archive with code signing (apple-id). 
2. Set env variable `SPACESHIP_AVOID_XCODE_API=true` to workaround https://github.com/bitrise-steplib/steps-xcode-archive/issues/287

**Comment by lpusok** [comment]
Looking into it.

**Comment by mthompson-spectra** [comment]
Thanks @lpusok! What do you think the timeline is for having the fix available in Bitrise? This is a blocker for us.

> Looking into it, can confirm that the Step fails with (SPACESHIP_AVOID_XCODE_API=true), will release a fix for it. Could not reproduce the original issue tough (#287).
