### ISSUE TITLE
could not find provisioning file

### ISSUE THREAD

**Issue by Young-Chowbus** [bitrise-steplib/steps-xcode-archive#293]
### Issue description
```Certificate and profile installer``` downloads all provisioning files but ```Xcode Archive & Export for iOS``` step could not find provisioning file

### Bitrise info

- Build URL: 
https://app.bitrise.io/build/81b74fe4-207d-45ca-99ef-16aca4f8b65a

- Log: 
Bitrise iOS development - (bundle identifier) (*************6)
exportType: development
team: Chowbus, Inc. (********)

certificates:
Apple Development: Young Zhang (******)
  serial: *****
  teamID: *****
devices:
 0b496271ffd627173093bd7fb4292
 e4083f38d9911ffd8a58b99a968163
 00008030-00014061

error: No profiles for '*******' were found: Xcode couldn't find any iOS App Development provisioning profiles matching '*******'

### Steps to reproduce

1. Upload certificate and Provisioning Profile
2. Start build
3. Certificate and profile installer -> downloads correct profile
4. Xcode Archive & Export for iOS -> No profiles for 'xxx.xxx.xxx' were found

**Comment by mjdelbianco** [comment]
any updates on this? i'm having exact same problem
