### ISSUE TITLE
got sign in problem when using xcode 14

### ISSUE THREAD

**Issue by jgroc-de** [bitrise-steplib/steps-xcode-archive#299]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.5.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE (no machine available)

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

when trying to launch this step, it fails with this error.

```
❌  error: Signing for "EXConstants-EXConstants" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'EXConstants-EXConstants' from project 'Pods')
❌  error: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'React-Core-AccessibilityResources' from project 'Pods')
```

The step seems to be well configure as it works with xcode 13.4
note: we are using 'expo eject' step just before.

### Bitrise info

- Build URL: https://app.bitrise.io/build/a65b7d4a-4c28-49f4-af7c-f3d1373798bd
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
[16:16:16] Creating the Archive ...
Starting the Archive ...
[16:16:16] $ set -o pipefail && xcodebuild "-workspace" "/Users/[REDACTED]/git/ios/rosaly.xcworkspace" "-scheme" "Rosaly" "-configuration" "Release" "-xcconfig" "/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/1739841700/temp.xcconfig" "archive" "-archivePath" "/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/xcodeArchive3694293394/Rosaly.xcarchive" "-destination" "generic/platform=iOS" | xcpretty
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Rosaly' from project 'Rosaly')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Rosaly' from project 'Rosaly')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
❌  error: Signing for "EXConstants-EXConstants" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'EXConstants-EXConstants' from project 'Pods')
❌  error: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'React-Core-AccessibilityResources' from project 'Pods')
Last lines of the Xcode's build log:
Build settings from configuration file '/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/1739841700/temp.xcconfig':
    COMPILER_INDEX_STORE_ENABLE = NO
  </pre>
</details>

### Steps to reproduce

1. make default xcode version 14
2. build project (just iphone)

**Comment by adrianb-further** [comment]
Hi, we encountered the same issue, @jgroc-de were you able to fix this issue?

**Comment by jgroc-de** [comment]
Nop, we went back to xcode 13.4.

**Comment by allan-simon** [comment]
same here, reverting to xcode 13.4 solve the issue

**Comment by gramiro** [comment]
Hello! Is there any progress on this ones? I'm facing the same issue with XCode and it'll be great to be able to build the project with latest SDK since today we have a new version of iOS coming out.

**Comment by kaancembertas** [comment]
Hello, we encounter the same issue. We cannot use our CI/CD pipelines because of that.

**Comment by radiodario** [comment]
Same here - any resolution would be greatly appreciated.

**Comment by ViktorVojtek** [comment]
+1

**Comment by rjindalrohit** [comment]
+1

**Comment by philipeneves** [comment]
+1
Encounterd the same issue when building to real device.
However, the quick fix for me was actually uncheck "Automatically manage signing" fill the Team field in both selects with warnings, check "Automatically manage signing" and fill the select (now only one is available). I did it to all pod targets with this light blue icon in the list on the left.
After that I've got another error about bitcode, I just set to "NO" Enable bitcode on the build settings tab (project target).

**Comment by umbertoghio** [comment]
@kaancembertas thank you!

I was getting errors for:
EXConstants-EXConstants, EXUpdates-EXUpdates, React-Core-AccessibilityResources, expo-dev-launcher-EXDevLauncher, expo-dev-menu-EXDevMenu

I managed to solve the eas local build by adding your code and changing only the team id:

```
post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    targetsToFix = ["EXConstants-EXConstants", "EXUpdates-EXUpdates", "React-Core-AccessibilityResources", "expo-dev-launcher-EXDevLauncher", "expo-dev-menu-EXDevMenu"];
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        if targetsToFix.include? target.name
          puts "Set development team for target #{target.name}"
          target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "MYTEAMID"
            config.build_settings["CODE_SIGN_IDENTITY"] = "Apple Distribution";
            config.build_settings["CODE_SIGN_STYLE"] = "Manual";
          end
        end
      end
    end
    
  end
```
Thanks!

**Comment by yvbeek** [comment]
Thanks for the information, it helped me to put together a solution for App Center.

This one will automatically grab the team identifier and projects:
```ruby
post_install do |installer|
  # Run the React-Native post install
  react_native_post_install(installer, :mac_catalyst_enabled => false)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  # Get the development team id from the main project
  dev_team_id = ""
  project = installer.aggregate_targets[0].user_project
  project.targets.each do |target|
    target.build_configurations.each do |config|
      if dev_team_id.empty? and !config.build_settings['DEVELOPMENT_TEAM'].nil?
        dev_team_id = config.build_settings['DEVELOPMENT_TEAM']
      end
    end
  end

  # Reconfigure the pods, update deployment target and signing settings
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
        config.build_settings['DEVELOPMENT_TEAM'] = dev_team_id
        config.build_settings['CODE_SIGN_IDENTITY'] = 'Apple Distribution';
        config.build_settings['CODE_SIGN_STYLE'] = 'Manual';
      end if

      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

Note: I also remove the deployment target from the Pods projects to prevent a few warnings, but you can remove that line if you want. It is not relevant for this issue.

**Comment by gabrielgautron** [comment]
It works thanks! I just had to remove `:mac_catalyst_enabled => false`from `react_native_post_install(installer, :mac_catalyst_enabled => false)`

**Comment by KrisLau** [comment]
Just to let any future people know that this has been fixed the react-native team in v0.70.3

- https://github.com/facebook/react-native/issues/34673#issuecomment-1276318220

**Comment by ArthurianX** [comment]
> any future people know that this has been fixed by the react-native team in v0.70.3

Looks good, but many of us can't simply upgrade 😢

**Comment by Fannolo** [comment]
> 

is there a way to not show the TEAM ID in your podfile?

**Comment by KrisLau** [comment]
@ArthurianX Yeah but there are already workarounds listed by other people for those who can't upgrade

**Comment by keremoge** [comment]
Add following code inside **post_install** of **Podfile**
Change **targetsToFix** to pod names that throws error when building. 
This fix is also made by React Native after version 0.70.3, so if you use RN 0.70.3 or above probably you don't need this workaround
```ruby
    # This is necessary for Xcode 14, because it signs resource bundles by default when building for devices
    # No need when using RN0.70.3** and above
    targetsToFix = ["MLKitTextRecognition-GoogleMVTextDetectorResources", "RNImageCropPicker-QBImagePicker", "React-Core-AccessibilityResources", "TOCropViewController-TOCropViewControllerBundle"];
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        if targetsToFix.include? resource_bundle_target.name
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
```

**Comment by thomasender** [comment]
@keremoge what is RN ?

**Comment by jvgeee** [comment]
If anyone's like me and none of the above fixed this, here's what worked:

- Try to do an archive build in XCode
- You'll get an error like the above
- Go to Pods in the left panel => open ExConstants-ExConstants
- Under "Signing and Capabilities" add your team and provisioning profile

Try to archive again (or in my case upload to AppCenter) and it'll work.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/2121331/223564455-25ef624d-b5ac-464c-b492-b0158d55f0e0.png">

**Comment by rdick** [comment]
> Add following code inside **post_install** of **Podfile** Change **targetsToFix** to pod names that throws error when building. This fix is also made by React Native after version 0.70.3, so if you use RN 0.70.3 or above probably you don't need this workaround
> 
> ```ruby
>     # This is necessary for Xcode 14, because it signs resource bundles by default when building for devices
>     # No need when using RN0.70.3** and above
>     targetsToFix = ["MLKitTextRecognition-GoogleMVTextDetectorResources", "RNImageCropPicker-QBImagePicker", "React-Core-AccessibilityResources", "TOCropViewController-TOCropViewControllerBundle"];
>     installer.target_installation_results.pod_target_installation_results
>       .each do |pod_name, target_installation_result|
>       target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
>         if targetsToFix.include? resource_bundle_target.name
>           resource_bundle_target.build_configurations.each do |config|
>             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>           end
>         end
>       end
>     end
> ```

Your solution was 50% correct.  I reused your code and made it work. 

Version: "react-native": "0.69.7",

`  
post_install do |installer|
    react_native_post_install(installer)

    targetsToFix = ["React-Core-AccessibilityResources", "EXConstants-EXConstants"];
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        if targetsToFix.include? resource_bundle_target.name
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
`

**Comment by RayHughes** [comment]
> > Add following code inside **post_install** of **Podfile** Change **targetsToFix** to pod names that throws error when building. This fix is also made by React Native after version 0.70.3, so if you use RN 0.70.3 or above probably you don't need this workaround
> > ```ruby
> >     # This is necessary for Xcode 14, because it signs resource bundles by default when building for devices
> >     # No need when using RN0.70.3** and above
> >     targetsToFix = ["MLKitTextRecognition-GoogleMVTextDetectorResources", "RNImageCropPicker-QBImagePicker", "React-Core-AccessibilityResources", "TOCropViewController-TOCropViewControllerBundle"];
> >     installer.target_installation_results.pod_target_installation_results
> >       .each do |pod_name, target_installation_result|
> >       target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
> >         if targetsToFix.include? resource_bundle_target.name
> >           resource_bundle_target.build_configurations.each do |config|
> >             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
> >           end
> >         end
> >       end
> >     end
> > ```
> 
> Your solution was 50% correct. I reused your code and made it work.
> 
> Version: "react-native": "0.69.7",
> 
> ```ruby
> post_install do |installer|
>     react_native_post_install(installer)
> 
>     targetsToFix = ["React-Core-AccessibilityResources", "EXConstants-EXConstants"];
>     installer.target_installation_results.pod_target_installation_results
>       .each do |pod_name, target_installation_result|
>       target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
>         if targetsToFix.include? resource_bundle_target.name
>           resource_bundle_target.build_configurations.each do |config|
>             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>           end
>         end
>       end
>     end
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> end
> ```

Thanks for saving me a headache!! Btw you have an Xtra end on the last line.

**Comment by jmoyers14** [comment]
I'm on react-native 0.71.4 and still experiencing this problem both locally with 14.2 and On bitrise Xcode 14.2.x, on macOS 13.2 (Ventura). Selecting a development team for the pod works on local but won't help for bitrise as the Pods are not checked into source control
