### ISSUE TITLE
Can't find the '/usr/local/opt/node/bin/node' binary to build the React Native bundle

### ISSUE THREAD

**Issue by smalomo** [bitrise-steplib/steps-xcode-archive#300]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.5.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

After several successful workflow builds, this started happening recently after I changed the Xcode version (to resolve a [different issue](https://github.com/bitrise-steplib/steps-xcode-archive/issues/249) from 13.1.x to 13.3.x

The xcode-archive step fails with the following error:
`Can't find the '/usr/local/opt/node/bin/node' binary to build the React Native bundle`

### Bitrise info

- Build URL: [https://app.bitrise.io/build/4068fa86-f885-4e48-89da-dbe0e4a460f1](https://app.bitrise.io/build/4068fa86-f885-4e48-89da-dbe0e4a460f1)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
▸ Processing Info.plist
▸ Running script 'Bundle React Native code and images'
❌  error: Can't find the '/usr/local/opt/node/bin/node' binary to build the React Native bundle.  
  </pre>
</details>

### Steps to reproduce
1. Run workflow

**Comment by ofalvai** [comment]
Hey @smalomo - This issue seems unrelated to the Xcode Archive step, we don't touch the node binary during the build with this step. If you still experience the problem, please open [a support ticket](https://support.bitrise.io/hc/en-us) and we'll take a look at the problem from other angles.
