### ISSUE TITLE
Please update to Xcode 7.3 or later

### ISSUE THREAD

**Issue by alexandreaugus** [bitrise-steplib/steps-xcode-archive#302]
Hi, I am getting this error using

Xcode Archive & Export for iOS
Version: 4.5.2
Xcode 13.2.x

Any ideas?

Checking development provisioning profiles
Using certificate for development distribution: Apple Development: XXX (XXX)
  Checking bundle id: com.XXX
  capabilities:
Exporting outputs...
failed to manage code signing: failed to ensure profiles: failed to find profile: failed to query Developer Portal: Apple provided the following error info:
Please update to Xcode 7.3 or later to continue developing with your Apple ID., stacktrace: /Users/[REDACTED]/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/client.rb:763:in `parse_response'
/Users/[REDACTED]/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/portal/portal_client.rb:669:in `provisioning_profiles_via_xcode_api'
/Users/[REDACTED]/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:319:in `all'
/private/var/folders/jw/g2nxpyn956dffdjs0vn8h9nm0000gn/T/1423197095/profiles.rb:21:in `list_profiles'
main.rb:46:in `<main>'

**Comment by wanderfeys** [comment]
Hi @alexandreaugus, yesterday i had same issue, Xcode step v4.5, Xcode 13.1, this solution helped me https://github.com/bitrise-steplib/steps-xcode-archive/issues/287#issuecomment-1075212701
