### ISSUE TITLE
Getting Failed to package /Users/vagrant/git on Flutter build

### ISSUE THREAD

**Issue by abdo400** [bitrise-steplib/steps-xcode-archive#304]
### Troubleshooting

- [ x ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 6
- Is the issue reproducible with the latest version? YES (At least for me)
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I am trying to build for Flutter, but I am getting this error whenever I am trying to.

   2022-07-26 22:14:14.708 xcodebuild[70157:103125] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

    Failed to package /Users/vagrant/git.
 Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/flutter_tools.7QXW0u/flutter_ios_build_temp_dirBrWNeo/temporary_xcresult_bundle

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
   2022-07-26 22:14:14.708 xcodebuild[70157:103125] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

    Failed to package /Users/vagrant/git.
 Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/flutter_tools.7QXW0u/flutter_ios_build_temp_dirBrWNeo/temporary_xcresult_bundle
  </pre>
</details>

### Steps to reproduce
My workflow is as follows
1. Activate SSH Key
2. Git Clone Repo
3. Certificate and profile installation
4. Flutter install
5. Bitrise.co Cache Pull
6. Script: 
rm -rf ./ios/Podfile.lock
flutter pub get
pod repo update
flutter build ios
(I get the issue at flutter build ios)
I have also used the special flutter build node but got the same result

**Comment by Roland-Bak** [comment]
Hello @abdo400 👋

In case you still experience this issue, could you please submit a ticket to us with all the details you can provide at https://support.bitrise.io/?

Please make sure to send us the URL of a related build and enable [Support User](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/)  so we can take a closer look! 🙂
