### ISSUE TITLE
`failed to create private key file`

### ISSUE THREAD

**Issue by Kamill90** [bitrise-steplib/steps-xcode-archive#306]
I use auto signing and I have both certs installed properly but after step `Downloading certificates...` i get error 
```Exporting outputs...
failed to create private key file: createtemp AuthKey_MIGTAgEAMBMGByqGS[...]9H3ZQ3q72WSmJtrh O5zT1cb5_*.p8: pattern contains path separator
````                                        
Uploaded certificates are in.p12 and have short, normal names. I cannot figure out where this error come from.

**Comment by ofalvai** [comment]
Hello @Kamill90 👋 

Can you please open a support ticket at our [Help Center](https://support.bitrise.io/hc/en-us)? This seems like an issue that will require enabling support access and that's easier over a private ticket than here on GitHub.
