### ISSUE TITLE
Archive failed, error: exit status 65

### ISSUE THREAD

**Issue by tthejus** [bitrise-steplib/steps-xcode-archive#312]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions. Yes
- Which version of the step is effected? 2.7.1 and 4.x
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Issue description
I have multiple workflows configured for different Environment. While the app builds successfully for `preprod` prod and recette qa workflows, it only fails for recette work flow with the following error.

The archive runs successfully when using  Xcode 13.0.x stack but fails when using Xcode13.4.x, Xcode14.X and so on. Problem only on Recette workflow. Tried to duplicate a working workflow and use it as a recette workflow, but I have the same error. 
Certificates and profiles seems valid.

Archive is successful when locally Archiving on Xcode.

### Bitrise info

- Build URL: xcode 13.4.1 : https://app.bitrise.io/build/0e6848b2-062c-4cf2-a9dd-4cce85e48e86
xcode14.0 : https://app.bitrise.io/build/f1d2bbf4-52cb-4dcb-9eac-399b97486ee8

- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 
13.4 : [raw-xcodebuild-output-2.log](https://github.com/bitrise-steplib/steps-xcode-archive/files/9659026/raw-xcodebuild-output-2.log)
14.0 : [xcodebuild-archive-2.log](https://github.com/bitrise-steplib/steps-xcode-archive/files/9658985/xcodebuild-archive-2.log)

<details>
  <pre>
 ** ARCHIVE FAILED **
The following build commands failed:
	Run custom shell script 'Run Script'
(1 failure)
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
	The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
	(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Archive failed, error: exit status 65```
  </pre>
</details>

**Comment by galahador** [comment]
I have the same problem, but in my case, Xcode13.0.x has the same problem. 
Also for some reason 80% of files. . . 
![Screen Shot 2022-10-07 at 13 10 09](https://user-images.githubusercontent.com/11472418/194540017-35a0cfd2-661f-4520-9fcb-296aa11a7a51.png)

**Comment by jgodonQobuz** [comment]
Hello there !

I think I've the same issue and this is really problematic 😰 

This bug just appears now that I'm moving my project from a Xcode project project.xcodeproj (where this workflow runs well) to a workspace project.xcworkspace that I need for several reasons...

I've update path as it should be in all workflow configurations... tried a lot of things but still this weird `command failed with exit status 65`

Any clue or things to do to learn more about this strange error ?

Thanks a lot for your answer

```
Failed to execute Step main logic:
  failed to archive the project:
    command failed with exit status 65 (set -o pipefail && xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/Qobuz.xcworkspace" "-scheme" "Qobuz-AdHoc" "-xcconfig" "/var/folders/9l/1ysg9vq51p37q0lgksxhdb9r0000gn/T/1132930427/temp.xcconfig" "-archivePath" "/var/folders/9l/1ysg9vq51p37q0lgksxhdb9r0000gn/T/xcodeArchive594967407/Qobuz.xcarchive" "-destination" "generic/platform=iOS" | xcpretty)
```

Xcode 14.x.x

**Comment by DamienBitrise** [comment]
> Run custom shell script 'Run Script'

Looks like there is an issue with your Run Script

```
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'PromisesObjC' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	Run custom shell script 'Run Script'
```

**Comment by DamienBitrise** [comment]
> Also for some reason 80% of files. . .

This likely means you have a secret with the value of `vagrant` set

**Comment by tthejus** [comment]
@DamienBitrise Do you have some inputs on my actual problem ? It would be great to advance on it. Still blocked by this issue.

**Comment by jgodonQobuz** [comment]
For my part, this was a Swift Lint Build phase error that was not clearly logged but the problem was coming from it... 
Thanks for help and have a good day

**Comment by Fallom25** [comment]
> @DamienBitrise Do you have some inputs on my actual problem ? It would be great to advance on it. Still blocked by this issue.

Hey Mate I have the same problem I used this guide and it works now. 
https://www.bigbinary.com/books/learn-react-native/handling-environment-specific-configurations-in-react-native

**Comment by dotdotcommadot** [comment]
Having the same problem on my Flutter project, after upgrading to Xcode 14

**Comment by Hamasn** [comment]
I also have the same problem, I am able to build with Bitrise with version xcode 14.0.1, but when use 14.1, it will be failed. and 
`Archive failed, error: exit status 65`
any tips?

**Comment by Alserk** [comment]
We also have the same problem using xcode version 13.4. Everything worked great until today.
Today it returns issue
`command failed with exit status 65 (set -o pipefail && xcodebuild "archive" "-workspace"`

**Comment by ThulaniMtetwa-Discovery** [comment]
How can I resolve this for my project?

**Comment by shahla-hafez** [comment]
Same error here

**Comment by juanOntiveros** [comment]
Any one could fix this issue? We are getting the same error with XCode 14.2

**Comment by sukesh-pfx** [comment]
Any updates?
Same issue for me 
Stack and machine type
> Xcode 14.1.x, on macOS 13.2 (Ventura)
> Intel Medium

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/64000239/228454431-9ad1434f-2a5a-4c00-b38f-b30cdd72ad2c.png">

**Comment by woliwa1** [comment]
> 

I met the same problem as you. How did you solve it?

**Comment by anhlq-supp** [comment]
I'm getting the same error today, has anyone resolved the issue?
```Failed to execute Step main logic:
  failed to archive the project:
    command failed with exit status 65 (xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/****.xcworkspace" "-scheme" "****" "-xcconfig" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/4186808971/temp.xcconfig" "-archivePath" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/xcodeArchive3739832971/****.xcarchive" "-destination" "generic/platform=iOS" "-skipPackagePluginValidation"):
      /Users/[REDACTED]/git/****Mutation.graphql.swift:35:12: error: initializer 'init(data:)' has different argument labels from those required by protocol 'SelectionSet' ('init(_dataDict:)') (exit code: 1)```

**Comment by bitrise-silver** [comment]
Hi everyone, exit status 65 can mean a lot of things related to Xcode archive process. I would kindly ask you do open support tickets so that you can be guided through case by case.

**Comment by liplylie** [comment]
Getting this as well: 

The following build commands failed:
	PhaseScriptExecution ... in target 'FBReactNativeSpec' from project 'Pods'

command failed with exit status 65

xcode 14.1.x, on macOS 13.2 (Ventura)
M1 Medium

**Comment by liplylie** [comment]
Was able to resolve this by installing the [nvm version step](https://bitrise.io/integrations/steps/nvm) and using node version 16.19.0.

**Comment by JZDesign** [comment]
Interesting thing to note, the command changed at some point even though the version wasn't changed. Perhaps this is the root cause?.

```
set -o pipefail && xcodebuild "-exportArchive" "-archivePath" "/var/folders/69/*******/T/xcodeArchive659969227/*******.xcarchive" "-exportPath" "/var/folders/69/*******/T/xcodeIPAExport1864044511/exported" "-exportOptionsPlist" "/var/folders/69/*******/T/xcodeIPAExport1864044511/export_options.plist" | xcpretty

👆 Succeeded


👇 Failed

   set -o pipefail && xcodebuild "archive" "-project" "/Users/[REDACTED]/git/iOS/*******/*******.xcodeproj" "-scheme" "Release" "-configuration" "Release" "-xcconfig" "/var/folders/69/*******/T/2495605686/temp.xcconfig" "-archivePath" "/var/folders/69/*******/T/xcodeArchive1375379806/*******.xcarchive" "-destination" "generic/platform=iOS" | xcpretty

**Comment by johannamelly** [comment]
I got the same error today with Xcode 14.3.x on macOS 13.2 (Ventura). I also tried with Xcode 15 but had the exact same issue.
Has anyone solved this?

```
Failed to execute Step main logic:
  failed to archive the project:
    command failed with exit status 65 (set -o pipefail && xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/ios/xxx.xcworkspace" "-scheme" "xxx" "-xcconfig" "/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/3208615793/temp.xcconfig" "-archivePath" "/var/folders/yy/6kcn9mkd5svdbqnznwf474f00000gn/T/xcodeArchive240265980/xxx.xcarchive" "-allowProvisioningUpdates" "-destination" "generic/platform=iOS" [REDACTED] xcpretty)
```

**Comment by anhlq-supp** [comment]
> I'm getting the same error today, has anyone resolved the issue?
> 
> ```
>   failed to archive the project:
>     command failed with exit status 65 (xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/****.xcworkspace" "-scheme" "****" "-xcconfig" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/4186808971/temp.xcconfig" "-archivePath" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/xcodeArchive3739832971/****.xcarchive" "-destination" "generic/platform=iOS" "-skipPackagePluginValidation"):
>       /Users/[REDACTED]/git/****Mutation.graphql.swift:35:12: error: initializer 'init(data:)' has different argument labels from those required by protocol 'SelectionSet' ('init(_dataDict:)') (exit code: 1)```
> ```
My case was caused by different library version between bitrise machine and my local machine. Solved it by pointing at specific version for every external library in my SPM. Hope this could help if you're in the same scenario.

**Comment by RichardLima** [comment]
> > I'm getting the same error today, has anyone resolved the issue?
> > ```
> >   failed to archive the project:
> >     command failed with exit status 65 (xcodebuild "archive" "-workspace" "/Users/[REDACTED]/git/****.xcworkspace" "-scheme" "****" "-xcconfig" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/4186808971/temp.xcconfig" "-archivePath" "/var/folders/xq/sfn_fz953jb36ptp2g68wc2r0000gn/T/xcodeArchive3739832971/****.xcarchive" "-destination" "generic/platform=iOS" "-skipPackagePluginValidation"):
> >       /Users/[REDACTED]/git/****Mutation.graphql.swift:35:12: error: initializer 'init(data:)' has different argument labels from those required by protocol 'SelectionSet' ('init(_dataDict:)') (exit code: 1)```
> > ```
> 
> My case was caused by different library version between bitrise machine and my local machine. Solved it by pointing at specific version for every external library in my SPM. Hope this could help if you're in the same scenario.

How did you notice that? Which library is this related to? tks

**Comment by RichardLima** [comment]
In my case, I fixed it after analyzing: xcodebuild-archive.log, and identified that the bitrise machine started to use an updated node version and that it has the problem: openssl-legacy-provider. :)

**Comment by johannamelly** [comment]
Hi, thanks for your answers! 

> In my case, I fixed it after analyzing: xcodebuild-archive.log, and identified that the bitrise machine started to use an updated node version and that it has the problem: openssl-legacy-provider. :)

It was exactly my problem! My node version was older so it was working fine locally, but not on Bitrise. I set a `NODE_OPTIONS` to `--openssl-legacy-provider` in the  Env Vars, and now everything is working well :)

**Comment by tomascenteno42** [comment]
Any news regarding this issue? All my builds are failing ):

**Comment by bitrise-silver** [comment]
Hello everyone, Bitrise build machines have various NodeJs versions so you need to lock down to the exact version your project expects. 
```
asdf install nodejs <version>
asdf global nodejs <version>
```
I also recommend you to commit `yarn.lock` or `npm-package.lock` then put NodeJs version in your package.json so that you can be notified if the versions in the build machine and your project are mismatched. 
Error 65 is a generic error when archiving, you are welcome to submit support requests for Bitrise to look into your particular cases.
