### ISSUE TITLE
Failed to process Step inputs:   issue with input ExportOptionsPlistContent: plist: type mismatch: tried to decode plist type `string' into value of type `map[string]interface {}' (exit code: 1)

### ISSUE THREAD

**Issue by Shahrukh0396** [bitrise-steplib/steps-xcode-archive#318]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.7.2
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE 

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Bitrise step xcode archive & Export ios has been failed when reading the export option plist file.

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/54e2ee8e-d184-42ee-b08f-7dd57540aed0)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
Failed to process Step inputs:
  issue with input ExportOptionsPlistContent: plist: type mismatch: tried to decode plist type `string' into value of type `map[string]interface {}'
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by tzuhan-bitrise** [comment]
Hi @Shahrukh0396 

Thank you for contacting Bitrise.

As the description of the input variable `ExportOptionsPlistContent` suggests, you need to input the **content** of the plist to that variable, not the **plist path**.
> Export options plist contentInsert variable
Specifies a plist file content that configures archive exporting.
If not specified, the Step will auto-generate it.

You can also leave it empty to let the step auto-generate it for you.

Hope this helps!
