### ISSUE TITLE
Xcode Archive & Export for iOS failed with exit status 65 for xCode 13.4 or later

### ISSUE THREAD

**Issue by aharodnikau** [bitrise-steplib/steps-xcode-archive#320]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? latest
- Is the issue reproducible with the latest version? YES and NO
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO 

### Useful information

Stack:
react-native: ^0.64.4

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

<img width="1502" alt="Screen Shot 2023-05-25 at 14 41 35" src="https://github.com/bitrise-steplib/steps-xcode-archive/assets/111116575/37240c3d-0f49-4e5a-ab45-fdd90462ce8f">

Build is failed with error(on screenshot above) since Xcode 13.4 or later. It works well locally using xcode 14.2

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 
[apps_901c73c350eb9ea0_695e01ea_9c18_44ab_9367_ff9b488d08d1_full.txt](https://github.com/bitrise-steplib/steps-xcode-archive/files/11569329/apps_901c73c350eb9ea0_695e01ea_9c18_44ab_9367_ff9b488d08d1_full.txt)

**Comment by andy-verida** [comment]
I got the same issue :(

**Comment by aharodnikau** [comment]
Solved it setting "Provide build setting from" to current scheme
<img width="986" alt="Screen Shot 2023-07-12 at 14 13 37" src="https://github.com/bitrise-steplib/steps-xcode-archive/assets/111116575/4b7b6996-0c04-44e5-b8d3-e2caca30c1f6">
