### ISSUE TITLE
Apple ID auth not working - 503 Service Temporarily Unavailable on various fastlane modules

### ISSUE THREAD

**Issue by y-hakutaku** [bitrise-steplib/steps-xcode-archive#362]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 5.2.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE...?

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description
Apple ID auth not working - 503 Service Temporarily Unavailable on various fastlane modules.

I'm not fully sure yet, but I believe the same issue is occurring in this step as well, so I have registered it as an issue to be addressed. Please check and confirm.
It seems that the issue can be resolved if you incorporate the updates addressed in fastlane.

I'm not confident in English, so if my expressions are unclear, please let me know.
- Related Issues
https://github.com/fastlane/fastlane/pull/26415
https://github.com/fastlane/fastlane/issues/26368

### Bitrise info

- Build URL: https://app.bitrise.io/build/2432fa11-cb40-4c68-b217-3febda00b0fb
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES 
- Log:
```
 Apple ID client created
[05:10:35] spaceship command failed with a retryable error, retrying (1. attempt)...
[05:11:37] spaceship command failed with a retryable error, retrying (2. attempt)...
[05:13:39] spaceship command failed with a retryable error, retrying (3. attempt)...
Failed to execute Step main logic:
  failed to manage code signing: Developer Portal client login failed: running command failed with error: spaceship command exited with status 1, output: Loading session from environment variable
  Session loaded from environment variable is not valid. Continuing with normal login.
  Apple ID authentication failed: <html>
  <head><title>503 Service Temporarily Unavailable</title></head>
  <body>
  <center><h1>503 Service Temporarily Unavailable</h1></center>
  <hr><center>Apple</center>
  </body>
  </html>
```

### Steps to reproduce

1. Run a workflow that includes Xcode Archive & Export for iOS

**Comment by shownChowbus** [comment]
+1

**Comment by SampleBotDanger** [comment]
+1
Probably caused by this issue:
https://github.com/fastlane/fastlane/issues/26368
The fix is comming for fastlane library 
https://github.com/fastlane/fastlane/issues/26368#issuecomment-2424190032

**Comment by y-hakutaku** [comment]
@SampleBotDanger @lifely 
Thank you, I think so too. However, I have no knowledge of Go language, so I am unable to create a pull request. Since the urgency is high, I have submitted this issue.

**Comment by y-hakutaku** [comment]
It seems that action has already started with go-xcode. 😄 

https://github.com/bitrise-io/go-xcode/commit/834b0ff07ee66b312b5a015d3bc21e56a155e308

**Comment by y-hakutaku** [comment]
merged 😄 
https://github.com/bitrise-io/go-xcode/pull/250

**Comment by danielpiva** [comment]
Hi, there :)

Unfortunately, I'm still getting the error with [`5.2.2`](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/5.2.2) 😢

```
Apple ID authentication failed: undefined method `unpack1' for nil:NilClass
[13:14:23] spaceship command failed with a retryable error, retrying (3. attempt)...
Failed to execute Step main logic:
  failed to manage code signing: Developer Portal client login failed: running command failed with error: spaceship command exited with status 1, output: Loading session from environment variable
  Session loaded from environment variable is not valid. Continuing with normal login.
  Starting SIRP Apple ID login
  Received SIRP signin init response: <html>
  <head><title>503 Service Temporarily Unavailable</title></head>
  <body>
  <center><h1>503 Service Temporarily Unavailable</h1></center>
  <hr><center>Apple</center>
  </body>
  </html>
  Apple ID authentication failed: undefined method `unpack1' for nil:NilClass
```

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/f461079d-71c4-499b-a930-86cbafdc8b56">

**Comment by lifely** [comment]
@danielpiva have you tried following the recommended steps on the `incident ticket` ? 

> https://status.bitrise.io/incidents/yjbmfwxwwh94

> If you're experiencing issues with your Apple ID connection, please remove the account and reconnect using your credentials

The updates worked for my flow, this ticket can be closed imho.

**Comment by danielpiva** [comment]
Hey, @lifely, I did reset the connection in the previous tests, but haven't removed and added again. About 10 minutes after commenting we had a run and it was all right.

Agreed, I also think this issue can be closed

**Comment by y-hakutaku** [comment]
:memo: If you still encounter an error with the latest version, please refer to this

https://status.bitrise.io/incidents/yjbmfwxwwh94
